import {createApp,reactive,ref,computed,watch,onMounted,onUnmounted,nextTick,h} from 'vue/dist/vue.esm-bundler.js';
import {ElMenu,ElMenuItem,ElSelect,ElOption,ElButton,ElDialog,ElInput,ElDatePicker,ElConfigProvider,ElMessage,ElLoading,ElMessageBox} from 'element-plus';
import zhCn from 'element-plus/es/locale/lang/zh-cn';
import 'element-plus/dist/index.css';
import 'element-plus/theme-chalk/dark/css-vars.css';
import './style.css';
const KEY='haocai-demo-v3';
const users={warehouse:{name:'林知远',role:'仓库管理员',dept:'行政部'},employee:{name:'陈小雨',role:'普通员工',dept:'产品部'},employeeAdmin:{name:'苏晴',role:'普通员工',dept:'行政部'},manager:{name:'周明',role:'部门负责人',dept:'产品部'},managerAdmin:{name:'赵岚',role:'部门负责人',dept:'行政部'},buyer:{name:'许安',role:'财务 / 采购人员',dept:'采购部'}};
const departments=['产品部','行政部','采购部'];
const names={dashboard:'总览',items:'物品档案',inbound:'入库管理',issues:'领用出库',requests:'采购申请',purchasing:'采购处理',alerts:'库存预警',records:'库存记录与统计'};
const icon=(paths)=>`<svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths}</svg>`;
const navIcons={
 dashboard:icon('<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>'),
 items:icon('<path d="M4 6.5 12 3l8 3.5v11L12 21l-8-3.5z"/><path d="M4 6.5 12 10l8-3.5M12 10v11"/>'),
 inbound:icon('<path d="M12 3v12m0 0-4-4m4 4 4-4"/><path d="M4 17v3h16v-3"/>'),
 issues:icon('<path d="M12 21V9m0 0-4 4m4-4 4 4"/><path d="M4 7V4h16v3"/>'),
 requests:icon('<path d="M8 4h-2a2 2 0 0 0-2 2v14h16V6a2 2 0 0 0-2-2h-2"/><path d="M9 3h6v3H9zM8 11h8M8 15h8"/>'),
 purchasing:icon('<path d="M3 7h18l-1.5 13h-15L3 7zM8 9V6a4 4 0 0 1 8 0v3"/>'),
 alerts:icon('<path d="M12 3 2.5 20h19L12 3zM12 9v5m0 3h.01"/>'),
 records:icon('<path d="M4 4h16v16H4zM8 15V9m4 6V6m4 9v-4"/>')};
const now=()=>new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString();const date=()=>now().slice(0,10);const days=(n)=>new Date(Date.now()+n*86400000-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10);
const uid=(prefix)=>prefix+'-'+Math.random().toString(36).slice(2,8).toUpperCase();
const seed=()=>({
 items:[
  {id:'i1',code:'BG-001',barcode:'6901234500011',name:'A4 复印纸',category:'办公耗材',spec:'80g / 500张',unit:'包',location:'A-01-03',safety:30,stock:128,price:25,active:true,expiry:''},
  {id:'i2',code:'BG-002',barcode:'6901234500028',name:'中性签字笔',category:'办公耗材',spec:'0.5mm / 黑色',unit:'盒',location:'A-02-01',safety:25,stock:18,price:18,active:true,expiry:''},
  {id:'i3',code:'IT-001',barcode:'6901234500035',name:'无线鼠标',category:'电子设备',spec:'蓝牙 / 2.4G 双模',unit:'个',location:'B-01-02',safety:10,stock:8,price:86,active:true,expiry:''},
  {id:'i4',code:'IT-002',barcode:'6901234500042',name:'机械键盘',category:'电子设备',spec:'87键 / 茶轴',unit:'个',location:'B-01-04',safety:5,stock:24,price:219,active:true,expiry:''},
  {id:'i5',code:'QJ-001',barcode:'6901234500059',name:'洗手液',category:'清洁用品',spec:'500ml / 瓶',unit:'瓶',location:'C-03-01',safety:20,stock:0,price:15,active:true,expiry:''},
  {id:'i6',code:'SP-001',barcode:'6901234500066',name:'挂耳咖啡',category:'食品饮品',spec:'10包 / 盒',unit:'盒',location:'C-01-02',safety:15,stock:36,price:49,active:true,expiry:days(19)},
  {id:'i7',code:'BG-003',barcode:'6901234500073',name:'打印机硒鼓',category:'办公耗材',spec:'黑色 / 3000页',unit:'个',location:'A-03-02',safety:8,stock:12,price:268,active:true,expiry:''},
  {id:'i8',code:'BG-004',barcode:'6901234500080',name:'碱性电池',category:'办公耗材',spec:'5号 / 20粒',unit:'盒',location:'A-03-05',safety:10,stock:4,price:32,active:true,expiry:''}
 ],
 issues:[
  {id:'LY-20260921-01',itemId:'i2',qty:3,requester:'苏晴',dept:'行政部',purpose:'前台及会议室日常使用',status:'pending',created:date()},
  {id:'LY-20260920-02',itemId:'i3',qty:2,requester:'陈小雨',dept:'产品部',purpose:'新员工办公设备',status:'approved',created:days(-1),operator:'林知远'},
  {id:'LY-20260918-03',itemId:'i1',qty:12,requester:'陈小雨',dept:'产品部',purpose:'项目评审资料打印',status:'completed',created:days(-3),completed:days(-2),operator:'林知远'},
  {id:'LY-20260917-04',itemId:'i3',qty:2,requester:'苏晴',dept:'行政部',purpose:'行政办公设备更换',status:'completed',created:days(-4),completed:days(-3),operator:'林知远'},
  {id:'LY-20260916-05',itemId:'i4',qty:1,requester:'陈小雨',dept:'产品部',purpose:'临时测试设备',status:'rejected',created:days(-5),operator:'林知远'}
 ],
 requests:[
  {id:'CG-20260921-01',lines:[{itemId:'i7',qty:5}],purpose:'研发打印设备耗材备用',expected:days(8),requester:'陈小雨',dept:'产品部',status:'draft',created:date()},
  {id:'CG-20260920-02',lines:[{itemId:'i1',qty:40},{itemId:'i6',qty:10}],purpose:'行政会议及公共区域物资补充',expected:days(7),requester:'苏晴',dept:'行政部',status:'submitted',created:days(-1)},
  {id:'CG-20260919-03',lines:[{itemId:'i4',qty:6}],purpose:'研发测试工位设备更新',expected:days(10),requester:'陈小雨',dept:'产品部',status:'rejected',created:days(-2),approver:'周明',rejectReason:'请补充设备领用人员及预算说明'},
  {id:'CG-20260918-04',lines:[{itemId:'i2',qty:30}],purpose:'补充日常办公文具',expected:days(6),requester:'陈小雨',dept:'产品部',status:'approved',created:days(-3),approver:'周明'},
  {id:'CG-20260917-05',lines:[{itemId:'i5',qty:40}],purpose:'公共区域清洁用品补充',expected:days(5),requester:'苏晴',dept:'行政部',status:'approved',created:days(-4),approver:'赵岚'},
  {id:'CG-20260916-06',lines:[{itemId:'i3',qty:10}],purpose:'产品团队办公设备补充',expected:days(3),requester:'陈小雨',dept:'产品部',status:'approved',created:days(-5),approver:'周明'},
  {id:'CG-20260914-07',lines:[{itemId:'i1',qty:20}],purpose:'行政档案集中打印备货',expected:days(-1),requester:'苏晴',dept:'行政部',status:'completed',created:days(-7),approver:'赵岚'}
 ],
 suppliers:['晨光供应链','京东企业购','得力集采中心','洁净优选'],
 dictionaries:{categories:['办公耗材','电子设备','清洁用品','食品饮品'],units:['个','包','盒','瓶','台'],locations:['A-01-03','A-02-01','A-03-02','A-03-05','B-01-02','B-01-04','C-03-01','C-01-02']},
 audits:[
  {id:'LOG-001',requestId:'CG-20260920-02',action:'创建申请',operator:'苏晴',role:'普通员工',time:days(-1)+' 09:10',detail:'保存包含 2 项物品的采购申请'},
  {id:'LOG-002',requestId:'CG-20260920-02',action:'提交审批',operator:'苏晴',role:'普通员工',time:days(-1)+' 09:18',detail:'提交至行政部负责人'},
  {id:'LOG-003',requestId:'CG-20260919-03',action:'创建申请',operator:'陈小雨',role:'普通员工',time:days(-2)+' 09:00',detail:'保存采购申请草稿'},
  {id:'LOG-004',requestId:'CG-20260919-03',action:'提交审批',operator:'陈小雨',role:'普通员工',time:days(-2)+' 09:20',detail:'提交至产品部负责人'},
  {id:'LOG-005',requestId:'CG-20260919-03',action:'审批驳回',operator:'周明',role:'部门负责人',time:days(-1)+' 10:20',detail:'请补充设备领用人员及预算说明'},
  {id:'LOG-006',requestId:'CG-20260918-04',action:'创建申请',operator:'陈小雨',role:'普通员工',time:days(-3)+' 09:10',detail:'保存采购申请草稿'},
  {id:'LOG-007',requestId:'CG-20260918-04',action:'提交审批',operator:'陈小雨',role:'普通员工',time:days(-3)+' 09:30',detail:'提交至产品部负责人'},
  {id:'LOG-008',requestId:'CG-20260918-04',action:'审批通过',operator:'周明',role:'部门负责人',time:days(-3)+' 11:05',detail:'生成 1 条待采购任务'},
  {id:'LOG-009',requestId:'CG-20260917-05',action:'创建申请',operator:'苏晴',role:'普通员工',time:days(-4)+' 08:50',detail:'保存采购申请草稿'},
  {id:'LOG-010',requestId:'CG-20260917-05',action:'提交审批',operator:'苏晴',role:'普通员工',time:days(-4)+' 09:05',detail:'提交至行政部负责人'},
  {id:'LOG-011',requestId:'CG-20260917-05',action:'审批通过',operator:'赵岚',role:'部门负责人',time:days(-4)+' 10:10',detail:'生成 1 条待采购任务'},
  {id:'LOG-012',requestId:'CG-20260917-05',action:'确认采购',operator:'许安',role:'财务 / 采购人员',time:days(-2)+' 14:30',detail:'洁净优选 · ¥15'},
  {id:'LOG-013',requestId:'CG-20260916-06',action:'创建申请',operator:'陈小雨',role:'普通员工',time:days(-5)+' 09:00',detail:'保存采购申请草稿'},
  {id:'LOG-014',requestId:'CG-20260916-06',action:'提交审批',operator:'陈小雨',role:'普通员工',time:days(-5)+' 09:20',detail:'提交至产品部负责人'},
  {id:'LOG-015',requestId:'CG-20260916-06',action:'审批通过',operator:'周明',role:'部门负责人',time:days(-5)+' 11:00',detail:'生成 1 条待采购任务'},
  {id:'LOG-016',requestId:'CG-20260916-06',action:'确认采购',operator:'许安',role:'财务 / 采购人员',time:days(-3)+' 13:40',detail:'京东企业购 · ¥86'},
  {id:'LOG-017',requestId:'CG-20260916-06',action:'采购部分到货',operator:'许安',role:'财务 / 采购人员',time:days(-1)+' 15:20',detail:'无线鼠标本次到货 4 个，累计 4/10'},
  {id:'LOG-018',requestId:'CG-20260914-07',action:'创建申请',operator:'苏晴',role:'普通员工',time:days(-7)+' 08:40',detail:'保存采购申请草稿'},
  {id:'LOG-019',requestId:'CG-20260914-07',action:'提交审批',operator:'苏晴',role:'普通员工',time:days(-7)+' 09:00',detail:'提交至行政部负责人'},
  {id:'LOG-020',requestId:'CG-20260914-07',action:'审批通过',operator:'赵岚',role:'部门负责人',time:days(-7)+' 10:20',detail:'生成 1 条待采购任务'},
  {id:'LOG-021',requestId:'CG-20260914-07',action:'确认采购',operator:'许安',role:'财务 / 采购人员',time:days(-5)+' 14:10',detail:'晨光供应链 · ¥25'},
  {id:'LOG-022',requestId:'CG-20260914-07',action:'采购到货完成',operator:'许安',role:'财务 / 采购人员',time:days(-2)+' 10:15',detail:'A4 复印纸到货 20 包'}
 ],
 tasks:[
  {id:'PC-20260918-01',requestId:'CG-20260918-04',itemId:'i2',qty:30,received:0,supplier:'',price:0,eta:'',status:'pending'},
  {id:'PC-20260917-02',requestId:'CG-20260917-05',itemId:'i5',qty:40,received:0,supplier:'洁净优选',price:15,eta:days(5),status:'ordered'},
  {id:'PC-20260916-03',requestId:'CG-20260916-06',itemId:'i3',qty:10,received:4,supplier:'京东企业购',price:86,eta:days(2),status:'partial'},
  {id:'PC-20260914-04',requestId:'CG-20260914-07',itemId:'i1',qty:20,received:20,supplier:'晨光供应链',price:25,eta:days(-1),status:'completed'}
 ],
 movements:[
  {id:'RK-OPEN-01',itemId:'i1',type:'采购入库',qty:120,price:25,supplier:'晨光供应链',batch:'A4-20260901',operator:'林知远',reason:'期初采购入库',time:days(-12)+' 09:30',dept:'行政部'},
  {id:'RK-OPEN-02',itemId:'i2',type:'库存调整',qty:18,price:18,supplier:'内部盘点',batch:'期初盘点',operator:'林知远',reason:'演示数据期初盘点',time:days(-12)+' 09:35',dept:'行政部'},
  {id:'RK-OPEN-03',itemId:'i3',type:'库存调整',qty:6,price:89,supplier:'内部盘点',batch:'期初盘点',operator:'林知远',reason:'演示数据期初盘点',time:days(-12)+' 09:40',dept:'行政部'},
  {id:'RK-OPEN-04',itemId:'i4',type:'库存调整',qty:24,price:219,supplier:'内部盘点',batch:'期初盘点',operator:'林知远',reason:'演示数据期初盘点',time:days(-12)+' 09:45',dept:'行政部'},
  {id:'RK-OPEN-05',itemId:'i6',type:'采购入库',qty:36,price:49,supplier:'京东企业购',batch:'CF-202609',operator:'林知远',reason:'食品饮品集中采购',time:days(-10)+' 11:10',dept:'行政部'},
  {id:'RK-OPEN-06',itemId:'i7',type:'库存调整',qty:12,price:268,supplier:'内部盘点',batch:'期初盘点',operator:'林知远',reason:'演示数据期初盘点',time:days(-10)+' 11:20',dept:'行政部'},
  {id:'RK-OPEN-07',itemId:'i8',type:'库存调整',qty:4,price:32,supplier:'内部盘点',batch:'期初盘点',operator:'林知远',reason:'演示数据期初盘点',time:days(-10)+' 11:25',dept:'行政部'},
  {id:'RK-PC-001',itemId:'i1',type:'采购入库',qty:20,price:25,supplier:'晨光供应链',batch:'A4-20260919',operator:'许安',reason:'采购任务 PC-20260914-04 分批到货',time:days(-2)+' 10:15',dept:'采购部',taskId:'PC-20260914-04'},
  {id:'RK-PC-002',itemId:'i3',type:'采购入库',qty:4,price:86,supplier:'京东企业购',batch:'MS-20260920',operator:'许安',reason:'采购任务 PC-20260916-03 分批到货',time:days(-1)+' 15:20',dept:'采购部',taskId:'PC-20260916-03'},
  {id:'CK-20260918-01',itemId:'i1',type:'领用出库',qty:-12,price:25,supplier:'',batch:'',operator:'林知远',reason:'项目评审资料打印 · 陈小雨',time:days(-2)+' 14:20',dept:'产品部',issueId:'LY-20260918-03'},
  {id:'CK-20260917-02',itemId:'i3',type:'领用出库',qty:-2,price:86,supplier:'',batch:'',operator:'林知远',reason:'行政办公设备更换 · 苏晴',time:days(-3)+' 16:10',dept:'行政部',issueId:'LY-20260917-04'}
 ],
 batches:[
  {id:'LOT-001',itemId:'i1',qty:108,code:'A4-20260901',expiry:'',supplier:'晨光供应链',receivedAt:days(-12)},
  {id:'LOT-002',itemId:'i1',qty:20,code:'A4-20260919',expiry:'',supplier:'晨光供应链',receivedAt:days(-2)},
  {id:'LOT-003',itemId:'i2',qty:18,code:'期初盘点',expiry:'',supplier:'内部盘点',receivedAt:days(-12)},
  {id:'LOT-004',itemId:'i3',qty:4,code:'期初盘点',expiry:'',supplier:'内部盘点',receivedAt:days(-12)},
  {id:'LOT-005',itemId:'i3',qty:4,code:'MS-20260920',expiry:'',supplier:'京东企业购',receivedAt:days(-1)},
  {id:'LOT-006',itemId:'i4',qty:24,code:'期初盘点',expiry:'',supplier:'内部盘点',receivedAt:days(-12)},
  {id:'LOT-007',itemId:'i6',qty:36,code:'CF-202609',expiry:days(19),supplier:'京东企业购',receivedAt:days(-10)},
  {id:'LOT-008',itemId:'i7',qty:12,code:'期初盘点',expiry:'',supplier:'内部盘点',receivedAt:days(-10)},
  {id:'LOT-009',itemId:'i8',qty:4,code:'期初盘点',expiry:'',supplier:'内部盘点',receivedAt:days(-10)}
 ],
 role:'warehouse'
});
let initial;try{initial=JSON.parse(localStorage.getItem(KEY))||seed()}catch{initial=seed()};if(!Array.isArray(initial.batches))initial.batches=initial.items.filter(x=>x.stock>0).map(x=>({id:uid('LOT'),itemId:x.id,qty:x.stock,code:'历史库存',expiry:x.expiry||'',supplier:'历史数据',receivedAt:date()}));if(!Array.isArray(initial.suppliers))initial.suppliers=[...new Set(['晨光供应链',...initial.tasks.map(x=>x.supplier),...initial.movements.filter(x=>x.type==='采购入库').map(x=>x.supplier)].filter(Boolean))];if(!initial.dictionaries)initial.dictionaries={categories:[...new Set(initial.items.map(x=>x.category).filter(Boolean))],units:[...new Set(initial.items.map(x=>x.unit).filter(Boolean))],locations:[...new Set(initial.items.map(x=>x.location).filter(Boolean))]};if(!Array.isArray(initial.audits))initial.audits=[];const state=reactive(initial),page=ref('dashboard'),filter=reactive({}),draftFilter=reactive({}),recordsTab=ref('movements');
const APPEARANCE_KEY='haocai-appearance-v1';
let savedAppearance;try{savedAppearance=JSON.parse(localStorage.getItem(APPEARANCE_KEY))||{}}catch{savedAppearance={}};
const appearance=reactive({mode:['light','dark'].includes(savedAppearance.mode)?savedAppearance.mode:'light',accent:['blue','violet','teal'].includes(savedAppearance.accent)?savedAppearance.accent:'blue',density:['comfortable','compact'].includes(savedAppearance.density)?savedAppearance.density:'comfortable'});
const accentOptions=[{value:'blue',label:'标准蓝',hex:'#1677ff'},{value:'violet',label:'紫罗兰',hex:'#7658d8'},{value:'teal',label:'青蓝',hex:'#168ca6'}];
watch(appearance,()=>{document.documentElement.dataset.theme=appearance.mode;document.documentElement.dataset.accent=appearance.accent;document.documentElement.dataset.density=appearance.density;document.documentElement.classList.toggle('dark',appearance.mode==='dark');try{localStorage.setItem(APPEARANCE_KEY,JSON.stringify(appearance))}catch{}},{deep:true,immediate:true});
const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){toast('浏览器无法保存本地数据，请检查存储设置')}};watch(state,save,{deep:true});const user=()=>users[state.role];const item=(id)=>state.items.find(x=>x.id===id);const fmt=(n)=>Number(n||0).toLocaleString('zh-CN');const money=(n)=>'¥'+Number(n||0).toLocaleString('zh-CN',{maximumFractionDigits:2});
function canAction(action){const [type,id]=action.split(':'),employee=['employee','employeeAdmin'].includes(state.role);if(['newItem','editItem','toggleItem','newInbound','approveIssue','rejectIssue','outIssue','returnIssue','manageDictionaries'].includes(type))return state.role==='warehouse';if(['newIssue','newRequest','purchaseFor'].includes(type))return employee;if(['editTask','receiveTask'].includes(type))return state.role==='buyer';if(['approveRequest','rejectRequest'].includes(type)){const req=state.requests.find(x=>x.id===id);return ['manager','managerAdmin'].includes(state.role)&&req?.dept===user().dept}if(['editRequest','submitRequest'].includes(type))return employee&&state.requests.find(x=>x.id===id)?.requester===user().name;return true}
function permissionMessage(action){const [type]=action.split(':');if(['newItem','editItem','toggleItem','newInbound','approveIssue','rejectIssue','outIssue','returnIssue','manageDictionaries'].includes(type))return'请切换仓库管理员执行此操作';if(['newIssue','newRequest','purchaseFor','editRequest','submitRequest'].includes(type))return'请切换普通员工发起或维护申请';if(['editTask','receiveTask'].includes(type))return'请切换财务 / 采购人员执行此操作';if(['approveRequest','rejectRequest'].includes(type))return'仅本部门负责人可审批该申请';return'当前角色无权执行此操作'}
const escapeHTML=(s)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const E=escapeHTML;
const locked=(id)=>state.issues.filter(x=>x.itemId===id&&x.status==='approved').reduce((a,x)=>a+x.qty,0);const available=(it)=>it.stock-locked(it.id);
const itemStatus=(it)=>!it.active?['已停用','neutral']:it.stock===0?['缺货','danger']:it.stock<it.safety?['低库存','warning']:['正常',''];
const badge=(text,kind='')=>`<span class="badge ${kind}">${E(text)}</span>`;
const statusBadge=(s)=>({draft:badge('草稿','neutral'),submitted:badge('待审批','warning'),approved:badge('已通过','blue'),rejected:badge('已驳回','danger'),completed:badge('已完成'),pending:badge('待审核','warning'),partial:badge('部分到货','blue'),ordered:badge('采购中','blue')}[s]||badge(s));
const taskStatusBadge=(s)=>({pending:badge('待采购','warning'),ordered:badge('采购中','blue'),partial:badge('部分到货','blue'),completed:badge('已完成')}[s]||badge(s));
const requestStatusBadge=(request)=>{if(request.status!=='approved')return statusBadge(request.status);const tasks=state.tasks.filter(task=>task.requestId===request.id);if(tasks.some(task=>task.status==='partial'))return badge('部分到货','blue');if(tasks.some(task=>task.status==='ordered'))return badge('采购中','blue');return badge('待采购','warning')};
const categoryIcons={
 '电子设备':icon('<rect x="4" y="5" width="16" height="12" rx="2"/><path d="M9 20h6m-3-3v3"/>'),
 '食品饮品':icon('<path d="M5 6h11v10a5.5 5.5 0 0 1-11 0V6zm11 2h2a2 2 0 0 1 0 4h-2M4 21h15"/>'),
 '清洁用品':icon('<path d="M8 4h8v3H8zM7 7h10l1 14H6L7 7zM10 12h4"/>'),
 '办公耗材':icon('<path d="M6 3h9l3 3v15H6V3zM15 3v4h4M9 11h6m-6 4h6"/>')};
const itCell=(it)=>it?`<div class="item-cell"><span class="item-icon">${categoryIcons[it.category]||navIcons.items}</span><div><strong>${E(it.name)}</strong><small>${E(it.code)} · ${E(it.spec)}</small></div></div>`:'物品已删除';
const personCell=(name,dept)=>`<div class="person-cell"><strong>${E(name||'—')}</strong><span class="person-dept">${E(dept||'—')}</span></div>`;
const btn=(text,action,cls='')=>`<button class="button small ${[cls,text==='编辑'?'edit-action':''].filter(Boolean).join(' ')}" data-action="${action}">${text}</button>`;
const filterLabels={itemsQ:'物品名称 / 编码',itemsCat:'物品分类',inQ:'入库物品',issueStatus:'领用状态',reqStatus:'申请状态',taskQ:'任务 / 物品',taskStatus:'采购状态',alertType:'预警类型'};
const decorateToolbar=(html,pageName)=>pageName==='records'?html:html.replace(/(<div class="toolbar">)([\s\S]*?)(<\/div>)/g,(_,open,fields,close)=>{fields=fields.replace(/<input\b[^>]*data-filter="([^"]+)"[^>]*>/g,(control,name)=>`<label class="list-filter-field"><span>${filterLabels[name]||'关键词'}</span>${control}</label>`).replace(/<select\b[^>]*data-filter="([^"]+)"[^>]*>[\s\S]*?<\/select>/g,(control,name)=>`<label class="list-filter-field"><span>${filterLabels[name]||'状态'}</span>${control}</label>`);return`${open}${fields}<div class="list-filter-actions"><button class="toolbar-search" data-action="searchFilters"><span class="button-icon">${controlIcons.search}</span>搜索</button><button class="toolbar-reset" data-action="clearFilters"><span class="button-icon">${controlIcons.reset}</span>重置</button></div>${close}`});
const uiIcons={money:icon('<path d="M3 7h18v12H3zM3 10h18M7 15h3"/>'),clock:icon('<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>'),alert:navIcons.alerts,items:navIcons.items};
const controlIcons={add:icon('<path d="M12 5v14M5 12h14"/>'),search:icon('<circle cx="11" cy="11" r="7"/><path d="m16 16 4 4"/>'),reset:icon('<path d="M4 9a8 8 0 1 1 2 8M4 9V4m0 5h5"/>'),export:icon('<path d="M12 15V3m0 0-4 4m4-4 4 4M5 13v7h14v-7"/>')};
const decorateHeadActions=(html)=>html.replace(/(<button[^>]*>)(?:\s*[＋+]\s*)?([^<]+)(<\/button>)/g,(_,open,text,close)=>`${open}<span class="button-icon">${/^\s*(?:新增|新建|发起|创建)/.test(text)?controlIcons.add:uiIcons.items}</span>${text.trim()}${close}`);
const refineIcons=(html)=>html.replace(/<span class="metric-icon">([^<]+)<\/span>/g,(_,symbol)=>`<span class="metric-icon">${({'▤':uiIcons.items,'¥':uiIcons.money,'◷':uiIcons.clock,'⚑':uiIcons.alert})[symbol]||uiIcons.items}</span>`).replace(/<button class="quick"([^>]*)><span>([^<]+)<\/span>/g,(_,attrs,symbol)=>`<button class="quick"${attrs}><span>${({'↗':navIcons.issues,'↙':navIcons.inbound,'▣':navIcons.requests})[symbol]||navIcons.dashboard}</span>`);
const applyPermissions=(html)=>html.replace(/<button([^>]*?)data-action="([^"]+)"([^>]*)>/g,(whole,before,action,after)=>canAction(action)?whole:`<button${before}data-action="${action}"${after} disabled title="${E(permissionMessage(action))}">`);
const heading=(title,subtitle,actions='')=>`<div class="page-head"><div><h1>${title}</h1>${subtitle?`<p class="subtitle">${subtitle}</p>`:''}</div><div class="head-actions">${decorateHeadActions(actions)}</div></div>`;
const table=(columns,rows,empty='暂无相关记录')=>`<div class="table-wrap"><table><thead><tr>${columns.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.join(''):`<tr><td colspan="${columns.length}"><div class="empty"><span>◎</span>${empty}</div></td></tr>`}</tbody></table></div>`;
const row=(cells)=>`<tr>${cells.map(x=>`<td>${x}</td>`).join('')}</tr>`;
const fieldLabel=(label)=>`<span class="field-label">${E(label.replace(/\s*\*\s*$/,''))}${label.includes('*')?'<span class="required-star" aria-label="必填">*</span>':''}</span>`;
const input=(label,name,type='text',value='',more='')=>`<label class="field">${fieldLabel(label)}<input name="${name}" type="${type}" value="${E(value)}" ${more}></label>`;
const select=(label,name,options,value='')=>`<label class="field">${fieldLabel(label)}<select name="${name}">${options.map(([v,t])=>`<option value="${E(v)}" ${String(v)===String(value)?'selected':''}>${E(t)}</option>`).join('')}</select></label>`;
const departmentOptions=()=>departments.map(dept=>[dept,dept]);
const supplierOptions=(current='')=>[...new Set([...state.suppliers,current].filter(Boolean))].map(name=>[name,name]);
const supplierSelect=(label,current='')=>`<label class="field supplier-field">${fieldLabel(label.replace('（采购入库必填）',''))}<select name="supplier" data-creatable="supplier" ${label.includes('*')?'required':''}><option value="">请选择或输入新供应商</option>${supplierOptions(current).map(([value,text])=>`<option value="${E(value)}" ${value===current?'selected':''}>${E(text)}</option>`).join('')}</select><small class="supplier-help">${label.includes('采购入库必填')?'采购入库必填 · ':''}可搜索或输入新名称后按回车新增</small></label>`;
const rememberSupplier=(name)=>{if(name&&!state.suppliers.includes(name))state.suppliers.push(name)};
const dictOptions=(type,current='')=>[...new Set([...(state.dictionaries[type]||[]),current].filter(Boolean))].map(value=>[value,value]);
const addAudit=(requestId,action,detail='')=>state.audits.push({id:uid('LOG'),requestId,action,operator:user().name,role:user().role,time:now().slice(0,16).replace('T',' '),detail});
function warningProgress(itemId,warningType){if(warningType==='已过期')return['已过期待处理','danger'];if(warningType==='即将过期')return['临期关注','warning'];const tasks=state.tasks.filter(task=>task.itemId===itemId&&task.status!=='completed');if(tasks.some(task=>task.status==='partial'))return['部分到货','blue'];if(tasks.some(task=>task.status==='ordered'))return['采购中','blue'];if(tasks.length)return['待采购','warning'];const request=state.requests.slice().reverse().find(current=>['draft','submitted','approved'].includes(current.status)&&current.lines.some(line=>line.itemId===itemId));if(request?.status==='submitted')return['待审批','warning'];if(request?.status==='approved')return['待采购','warning'];if(request?.status==='draft')return['草稿待提交','neutral'];return['待采购','warning']}
const itemOptions=(active=true)=>state.items.filter(x=>!active||x.active).map(x=>[x.id,`${x.name} (${x.code}) · 可用 ${available(x)} ${x.unit}`]);
function warnings(){const today=date(),soonUntil=days(30);return state.items.filter(x=>x.active).flatMap(x=>{const result=[],lots=state.batches.filter(b=>b.itemId===x.id&&b.qty>0&&b.expiry),expired=lots.filter(b=>b.expiry<today),expiring=lots.filter(b=>b.expiry>=today&&b.expiry<=soonUntil);if(x.stock===0)result.push({it:x,type:'缺货',kind:'danger'});else if(x.stock<x.safety)result.push({it:x,type:'低库存',kind:'warning'});for(const [type,kind,batches] of [['已过期','danger',expired],['即将过期','warning',expiring]])if(batches.length)result.push({it:x,type,kind,expiry:batches.map(b=>b.expiry).sort()[0],expiringQty:batches.reduce((n,b)=>n+b.qty,0)});return result})}
function dashboard(){
 const alerts=warnings().sort((a,b)=>({'已过期':0,'缺货':1,'低库存':2,'即将过期':3}[a.type]??4)-({'已过期':0,'缺货':1,'低库存':2,'即将过期':3}[b.type]??4));
 const stockValue=state.items.reduce((sum,x)=>sum+x.stock*x.price,0);
 let todos=[];
 if(state.role==='warehouse')todos=[['待审核领用',state.issues.filter(x=>x.status==='pending').length,'issues','审核员工领用申请'],['待执行出库',state.issues.filter(x=>x.status==='approved').length,'issues','完成已通过的领用']];
 else if(state.role==='buyer')todos=[['待处理采购',state.tasks.filter(x=>x.status!=='completed').length,'purchasing','跟进采购与到货']];
 else if(state.role==='manager'||state.role==='managerAdmin')todos=[['待审批采购',state.requests.filter(x=>x.status==='submitted'&&x.dept===user().dept).length,'requests','处理本部门采购申请']];
 else todos=[['待提交草稿',state.requests.filter(x=>x.requester===user().name&&['draft','rejected'].includes(x.status)).length,'requests','完善并提交采购申请'],['领用申请进度',state.issues.filter(x=>x.requester===user().name&&['pending','approved'].includes(x.status)).length,'issues','查看尚未出库的申请']];
 const todoCount=todos.reduce((sum,x)=>sum+x[1],0);
 const stat=(label,value,route,iconHtml)=>'<button class="dash-stat" data-page="'+route+'"><span class="dash-stat-icon">'+iconHtml+'</span><span class="dash-stat-content"><span class="dash-stat-label">'+label+'</span><strong>'+value+'</strong></span></button>';
 const alertRows=alerts.slice(0,4).map(a=>{const progress=warningProgress(a.it.id,a.type);return'<div class="dash-alert-row"><span class="dash-alert-icon">'+(categoryIcons[a.it.category]||navIcons.items)+'</span><span class="dash-row-main"><b>'+E(a.it.name)+'</b><small>'+E(a.it.code)+' · 库存 '+a.it.stock+' / 安全 '+a.it.safety+' '+E(a.it.unit)+'</small></span>'+badge(a.type,a.kind)+badge(progress[0],progress[1])+'</div>'}).join('')||'<div class="dash-empty">目前没有库存预警，库存状态良好。</div>';
 const todoRows=todos.filter(x=>x[1]>0).map(x=>'<button class="dash-todo-row" data-page="'+x[2]+'"><span class="dash-todo-mark">'+navIcons.requests+'</span><span><b>'+x[0]+'</b><small>'+x[3]+'</small></span><strong>'+x[1]+'</strong></button>').join('')||'<div class="dash-empty">当前角色没有待处理事项。</div>';
 const movementRows=state.movements.slice().reverse().slice(0,4).map(m=>'<div class="dash-movement-row"><span class="dash-movement-mark '+(m.qty<0?'out':'')+'">'+(m.qty<0?navIcons.issues:navIcons.inbound)+'</span><span class="dash-row-main"><b>'+E(m.type)+' · '+E(item(m.itemId)?.name||'物品')+'</b><small>'+E(m.operator)+' · '+E(m.reason)+'</small></span><span class="dash-movement-meta"><b class="'+(m.qty<0?'negative':'positive')+'">'+(m.qty>0?'+':'')+m.qty+' '+E(item(m.itemId)?.unit||'')+'</b><small>'+E(m.time.slice(5))+'</small></span></div>').join('')||'<div class="dash-empty">暂无库存动态。</div>';
 const quick=[['newIssue','申请领用','提交物品领用',navIcons.issues],['newInbound','登记入库','更新实际库存',navIcons.inbound],['newRequest','采购申请','批量申请物品',navIcons.requests]].map(x=>'<button class="dash-quick" data-action="'+x[0]+'"><span class="dash-quick-icon">'+x[3]+'</span><span><b>'+x[1]+'</b><small>'+x[2]+'</small></span></button>').join('');
 return '<div class="dashboard-head"><div class="dashboard-title"><h1>工作台总览</h1><p>你好，'+E(user().name)+'。这里是需要关注的业务动态。</p></div><div class="dashboard-head-actions"><span class="dashboard-date">'+E(date())+' <i></i> '+E(user().dept)+'</span><button class="button primary" data-action="newRequest"><span class="button-icon">'+controlIcons.add+'</span>新建采购申请</button></div></div>'
 +'<div class="dash-stats">'+stat('在库物品',fmt(state.items.filter(x=>x.active).length),'items',navIcons.items)+stat('库存金额',money(stockValue),'records',uiIcons.money)+stat('我的待办',fmt(todoCount),state.role==='buyer'?'purchasing':state.role==='warehouse'?'issues':'requests',uiIcons.clock)+stat('库存预警',fmt(alerts.length),'alerts',navIcons.alerts)+'</div>'
 +'<div class="dashboard-layout"><div class="dashboard-column"><section class="card dash-panel"><div class="dash-panel-head"><h2>库存预警</h2><button class="text-link" data-page="alerts">查看全部</button></div><div class="dash-panel-body">'+alertRows+'</div></section><section class="card dash-panel"><div class="dash-panel-head"><h2>最近库存动态</h2><button class="text-link" data-page="records">查看流水</button></div><div class="dash-panel-body">'+movementRows+'</div></section></div><div class="dashboard-column"><section class="card dash-panel"><div class="dash-panel-head"><h2>我的待办</h2></div><div class="dash-panel-body">'+todoRows+'</div></section><section class="card dash-panel"><div class="dash-panel-head"><h2>快捷操作</h2></div><div class="dash-panel-body">'+quick+'</div></section></div></div>';
}
function items(){let q=(filter.itemsQ||'').toLowerCase(),cat=filter.itemsCat||'',arr=state.items.filter(x=>(x.name+x.code+x.barcode).toLowerCase().includes(q)&&(!cat||x.category===cat));return heading('物品档案','集中管理物品信息，实时掌握库存状态。',`<button class="button" data-action="manageDictionaries">基础字典</button><button class="button primary" data-action="newItem">＋ 新增物品</button>`,'MASTER DATA / 物品档案')+`<div class="card"><div class="toolbar"><input class="search" placeholder="搜索物品名称 / 编码 / 条形码" data-filter="itemsQ" value="${E(filter.itemsQ||'')}"><select class="filter" data-filter="itemsCat"><option value="">全部分类</option>${[...new Set(state.items.map(x=>x.category))].map(c=>`<option ${cat===c?'selected':''}>${E(c)}</option>`).join('')}</select></div>${table(['物品信息','分类 / 位置','当前库存','可用 / 锁定','安全库存','状态','操作'],arr.map(x=>row([itCell(x),`${E(x.category)}<br><span class="mono">${E(x.location)}</span>`,`<strong>${x.stock}</strong> ${E(x.unit)}`,`${available(x)} / ${locked(x)}`,`${x.safety} ${E(x.unit)}`,badge(...itemStatus(x)),`<div class="table-actions">${btn('批次',`itemBatches:${x.id}`)}${btn('编辑',`editItem:${x.id}`)}${btn(x.active?'停用':'启用',`toggleItem:${x.id}`,x.active?'danger':'')}</div>`])))}</div>`}
function inbound(){let q=(filter.inQ||'').toLowerCase(),arr=state.movements.filter(m=>m.qty>0&&['采购入库','退货入库','库存调整'].includes(m.type)&&(item(m.itemId)?.name||'').toLowerCase().includes(q)).slice().reverse();return heading('入库管理','采购到货、退回入库与库存调整，完成后实时更新库存。',`<button class="button primary" data-action="newInbound">＋ 新增入库</button>`,'STOCK IN / 入库管理')+`<div class="hint">采购任务请在「采购处理」登记实际到货，支持分批入库；此处登记独立采购入库、退货入库及库存调整。</div><div class="card"><div class="toolbar"><input class="search" placeholder="搜索入库物品" data-filter="inQ" value="${E(filter.inQ||'')}"></div>${table(['入库单号 / 时间','物品','类型 / 批次','入库数量','单价','供应商','操作人','操作'],arr.map(m=>row([`<strong>${E(m.id)}</strong><br><small>${E(m.time)}</small>`,itCell(item(m.itemId)),`${badge(m.type,m.type==='库存调整'?'blue':'')}<br><small>${E(m.batch||'—')}</small>`,`<span class="stock-qty positive"><strong>+${m.qty}</strong><small>${E(item(m.itemId)?.unit||'')}</small></span>`,`<span class="stock-price">${money(m.price)}</span>`,E(m.supplier||'—'),E(m.operator||'—'),`<div class="table-actions">${btn('详情',`inboundDetail:${m.id}`)}</div>`])))}</div>`}
function issues(){
 let s=filter.issueStatus||'',arr=state.issues.filter(x=>!s||x.status===s).slice().reverse();
 return heading('领用出库','员工发起申请，仓库审核并执行出库。',`<button class="button primary" data-action="newIssue">＋ 发起领用申请</button>`)
 +`<div class="hint">审核通过后锁定数量，实际出库时扣减库存；已出库领用单可关联退回。</div><div class="card"><div class="toolbar"><select class="filter" data-filter="issueStatus">${[['','全部状态'],['pending','待审核'],['approved','已通过待出库'],['rejected','已驳回'],['completed','已出库']].map(([v,t])=>`<option value="${v}" ${s===v?'selected':''}>${t}</option>`).join('')}</select></div>`
 +table(['申请编号 / 日期','领用物品','领用人 / 部门','数量','状态','操作'],arr.map(x=>{
  let returned=returnedQty(x.id),remaining=x.qty-returned;
  return row([`<strong>${E(x.id)}</strong><br><small>${E(x.created)}</small>`,itCell(item(x.itemId)),personCell(x.requester,x.dept),`${x.qty} ${E(item(x.itemId)?.unit||'')}${returned?`<br><small>已退 ${returned} ${E(item(x.itemId)?.unit||'')}</small>`:''}`,statusBadge(x.status),`<div class="table-actions">${x.status==='pending'?btn('审核通过',`approveIssue:${x.id}`)+btn('驳回',`rejectIssue:${x.id}`,'danger'):''}${x.status==='approved'?btn('执行出库',`outIssue:${x.id}`,'primary'):''}${x.status==='completed'?btn('详情',`outboundDetail:${x.id}`):''}${x.status==='completed'&&remaining>0?btn('登记退回',`returnIssue:${x.id}`,'return-action'):''}${x.status==='completed'&&remaining===0?'<span class="mono">已全部退回</span>':''}</div>`])
 }))+'</div>'
}
function requests(){let s=filter.reqStatus||'',arr=state.requests.filter(x=>!s||x.status===s).slice().reverse();return heading('采购申请','申请人提交需求，审批通过后由采购人员完善报价并登记到货。',`<button class="button primary" data-action="newRequest">＋ 新建采购申请</button>`,'PROCUREMENT / 采购申请')+`<div class="card"><div class="toolbar"><select class="filter" data-filter="reqStatus">${[['','全部状态'],['draft','草稿'],['submitted','待审批'],['approved','采购处理中'],['rejected','已驳回'],['completed','已完成']].map(([v,t])=>`<option value="${v}" ${s===v?'selected':''}>${t}</option>`).join('')}</select></div>${table(['申请编号 / 日期','申请物品','申请人 / 部门','期望到货','业务进度','操作'],arr.map(x=>row([`<strong>${E(x.id)}</strong><br><small>${E(x.created)}</small>`,`<strong>${x.lines.length} 种物品</strong><br><small>${x.lines.map(l=>`${E(item(l.itemId)?.name)} × ${l.qty}`).join('、')}</small>`,personCell(x.requester,x.dept),E(x.expected),requestStatusBadge(x),`<div class="table-actions">${btn('详情',`viewRequest:${x.id}`)}${x.status==='draft'||x.status==='rejected'?btn('编辑',`editRequest:${x.id}`)+btn('提交',`submitRequest:${x.id}`,'primary'):''}${x.status==='submitted'?btn('审批通过',`approveRequest:${x.id}`,'primary')+btn('驳回',`rejectRequest:${x.id}`,'danger'):''}</div>`])))}</div>`}
function purchasing(){
 const q=(filter.taskQ||'').toLowerCase(),selectedStatus=filter.taskStatus||'',all=state.tasks.slice().reverse(),visible=all.filter(t=>{const it=item(t.itemId);return(!q||(t.id+t.requestId+t.supplier+(it?.name||'')+(it?.code||'')).toLowerCase().includes(q))&&(!selectedStatus||t.status===selectedStatus)});
 const rows=visible.map(t=>{
  const it=item(t.itemId),hasInfo=Boolean(t.supplier&&t.price&&t.eta);
  const quote=hasInfo
   ?`<div class="purchase-quote"><strong>${E(t.supplier)}</strong><span><small>采购单价</small>${money(t.price)} / ${E(it?.unit||'件')}</span></div>`
   :'<div class="purchase-quote is-empty"><strong>尚未完善</strong><span>请填写供应商与采购单价</span></div>';
  const eta=t.eta?`<div class="purchase-date"><strong>${E(t.eta)}</strong></div>`:'<span class="purchase-pending">待安排</span>';
  let actions;
  if(t.status==='completed')actions=btn('入库记录',`taskMovements:${t.id}`);
  else if(t.status==='partial')actions=btn('继续到货',`receiveTask:${t.id}`,'primary');
  else if(t.status==='ordered')actions=btn('调整采购',`editTask:${t.id}`,'purchase-adjust')+btn('登记到货',`receiveTask:${t.id}`,'primary');
  else actions=btn('完善采购',`editTask:${t.id}`,'primary');
  return row([`<strong>${E(t.id)}</strong><br><small>申请 ${E(t.requestId)}</small>`,itCell(it),`<strong>${t.received} / ${t.qty} ${E(it?.unit||'')}</strong><div class="progress"><span style="width:${Math.min(100,t.received/t.qty*100)}%"></span></div>`,quote,eta,taskStatusBadge(t.status),`<div class="table-actions">${actions}</div>`]);
 });
 const toolbar=`<div class="toolbar"><input class="search" placeholder="输入任务号、物品或供应商" data-filter="taskQ" value="${E(filter.taskQ||'')}"><select class="filter" data-filter="taskStatus">${[['','全部状态'],['pending','待采购'],['ordered','采购中'],['partial','部分到货'],['completed','已完成']].map(([value,label])=>`<option value="${value}" ${selectedStatus===value?'selected':''}>${label}</option>`).join('')}</select></div>`;
 return heading('采购处理','统一跟进采购报价、到货进度与入库结果。')+`<div class="card purchasing-card">${toolbar}${table(['采购任务 / 来源','物品','数量 / 到货进度','采购报价','预计到货','状态','操作'],rows,'当前条件下没有采购任务')}</div>`;
}
function alerts(){const all=warnings(),selectedType=filter.alertType||'',visible=all.filter(x=>!selectedType||x.type===selectedType),types=['缺货','低库存','即将过期','已过期'];return heading('库存预警','分别查看缺货、低库存和临期库存，库存恢复后预警将自动解除。',`<button class="button" data-page="items">查看全部物品</button><button class="button primary" data-action="newRequest">创建采购申请</button>`)+`<div class="metrics alert-metrics"><div class="metric"><span class="metric-icon">⚑</span><label>预警总数</label><strong>${all.length}</strong></div>${types.map(type=>`<div class="metric"><label>${type}</label><strong>${all.filter(x=>x.type===type).length}</strong></div>`).join('')}</div><div class="card alert-list-card"><div class="toolbar"><select class="filter" data-filter="alertType">${['',...types].map(type=>`<option value="${type}" ${selectedType===type?'selected':''}>${type||'全部预警'}</option>`).join('')}</select></div>${table(['物品','预警类型','当前 / 安全库存','批次效期','处理建议'],visible.map(({it,type,kind,expiry,expiringQty})=>row([itCell(it),badge(type,kind),`${it.stock} / ${it.safety} ${E(it.unit)}`,E(expiry||'不适用'),type==='已过期'?`隔离并核查 ${expiringQty} ${E(it.unit)}过期批次`:type==='即将过期'?`优先处理 ${expiringQty} ${E(it.unit)}临期批次`:`建议补货 ${Math.max(it.safety*2-it.stock,1)} ${E(it.unit)}`])),'暂无预警，库存状态良好')}</div>`}
function records(){
 const q=(filter.recQ||'').toLowerCase(),person=(filter.personQ||'').toLowerCase(),dept=filter.recDept||'',cat=filter.recCat||'',typ=filter.recType||'',from=filter.recFrom||'',to=filter.recTo||'';
 const movements=state.movements.filter(m=>{let it=item(m.itemId);return(it?.name||'').toLowerCase().includes(q)&&(!dept||m.dept===dept)&&(!cat||it?.category===cat)&&(!typ||m.type===typ)&&(!from||m.time.slice(0,10)>=from)&&(!to||m.time.slice(0,10)<=to)}).slice().reverse();
 const issues=state.issues.filter(x=>x.status==='completed'&&(!dept||x.dept===dept)&&x.requester.toLowerCase().includes(person)&&(!from||(x.completed||x.created)>=from)&&(!to||(x.completed||x.created)<=to)).slice().reverse();
 const ins=movements.reduce((n,m)=>n+Math.max(0,m.qty),0),outs=movements.reduce((n,m)=>n+Math.max(0,-m.qty),0),stock=state.items.reduce((n,x)=>n+x.stock,0),value=state.items.reduce((n,x)=>n+x.stock*x.price,0),detail=recordsTab.value==='issues';
 const departmentsInRecords=[...new Set([...state.movements.map(x=>x.dept),...state.issues.map(x=>x.dept)])].filter(Boolean);
 const filters=`<div class="records-filters ${detail?'is-detail':''}"><div class="toolbar"><label class="record-filter-field search-field"><span>${detail?'领用人':'物品名称'}</span><input class="search" placeholder="${detail?'输入领用人姓名':'输入名称或编码'}" data-filter="${detail?'personQ':'recQ'}" value="${E(detail?filter.personQ||'':filter.recQ||'')}"></label><label class="record-filter-field dept-field"><span>部门</span><select class="filter" data-filter="recDept"><option value="">全部部门</option>${departmentsInRecords.map(x=>`<option ${dept===x?'selected':''}>${E(x)}</option>`).join('')}</select></label>${detail?'':`<label class="record-filter-field"><span>物品分类</span><select class="filter" data-filter="recCat"><option value="">全部分类</option>${[...new Set(state.items.map(x=>x.category))].map(x=>`<option ${cat===x?'selected':''}>${E(x)}</option>`).join('')}</select></label><label class="record-filter-field"><span>操作类型</span><select class="filter" data-filter="recType"><option value="">全部类型</option>${[...new Set(state.movements.map(x=>x.type))].map(x=>`<option ${typ===x?'selected':''}>${E(x)}</option>`).join('')}</select></label>`}<label class="record-filter-field date-field"><span>开始日期</span><input class="filter" type="date" data-filter="recFrom" value="${E(from)}"></label><label class="record-filter-field date-field"><span>结束日期</span><input class="filter" type="date" data-filter="recTo" value="${E(to)}"></label><div class="records-filter-actions"><button class="toolbar-search" data-action="searchFilters"><span class="button-icon">${controlIcons.search}</span>搜索</button><button class="toolbar-reset" data-action="clearFilters"><span class="button-icon">${controlIcons.reset}</span>重置</button></div></div></div>`;
 const movementTable=table(['时间 / 单号','物品 / 分类','操作类型','变动数量','操作人 / 部门','变化原因'],movements.map(m=>row([`<strong>${E(m.time)}</strong><br><small class="mono">${E(m.id)}</small>`,`${itCell(item(m.itemId))}<small class="category-line">${E(item(m.itemId)?.category)}</small>`,badge(m.type,m.qty<0?'warning':'blue'),`<strong class="${m.qty>0?'positive':'negative'}">${m.qty>0?'+':''}${m.qty}</strong> ${E(item(m.itemId)?.unit||'')}`,personCell(m.operator,m.dept),E(m.reason)])),'当前条件下没有库存流水');
 const issueTable=table(['领用人 / 部门','领用物品','数量','用途','出库日期'],issues.map(x=>row([personCell(x.requester,x.dept),itCell(item(x.itemId)),`<strong>${x.qty}</strong> ${E(item(x.itemId)?.unit||'')}`,E(x.purpose),E(x.completed||x.created)])),'当前条件下没有领用记录');
 return heading('库存记录','')+`<div class="record-summary"><div><span>筛选入库</span><i>${navIcons.inbound}</i><strong class="positive">+${fmt(ins)}</strong></div><div><span>筛选出库</span><i>${navIcons.issues}</i><strong class="negative">−${fmt(outs)}</strong></div><div><span>当前库存</span><i>${navIcons.items}</i><strong>${fmt(stock)}</strong></div><div><span>库存金额</span><i>${uiIcons.money}</i><strong>${money(value)}</strong></div></div><div class="card records-panel"><div class="records-panel-head"><div class="record-tabs"><button type="button" class="${detail?'':'active'}" data-action="recordTab:movements">库存流水 <small>${movements.length}</small></button><button type="button" class="${detail?'active':''}" data-action="recordTab:issues">领用明细 <small>${issues.length}</small></button></div><button class="toolbar-export records-head-export" data-action="exportRecords"><span class="button-icon">${controlIcons.export}</span>导出${detail?'领用明细':'库存流水'}</button></div>${filters}${detail?issueTable:movementTable}<div class="records-footer">显示 ${detail?issues.length:movements.length} 条记录 · 数据保存在当前浏览器</div></div>`;
}

function toast(message,type='success'){ElMessage({message,type,placement:'top-right',duration:3000,showClose:true,offset:78})}
let operationBusy=false;
function runWithLoading(work,target){if(operationBusy)return;operationBusy=true;const loading=ElLoading.service({target:target||document.body,lock:false,text:'正在处理，请稍候…',background:'rgba(255,255,255,.68)'});setTimeout(()=>{try{work()}finally{loading.close();operationBusy=false}},450)}
const modalControlApps=[],enhancedControlModels=new WeakMap();let modalShellApp=null;
function enhanceDialogControls(root=document.querySelector('#dialogForm')){if(!root)return;for(const control of [...root.querySelectorAll('select,input:not([type="hidden"]):not([data-native]),textarea')]){
 const isSelect=control.tagName==='SELECT',isDate=control.type==='date',isText=!isSelect&&!isDate,name=control.name,model=ref(control.value||''),options=isSelect?[...control.options].map(x=>({value:x.value,label:x.textContent,disabled:x.disabled})):[],min=control.getAttribute('min'),creatable=control.dataset.creatable==='supplier';
 const host=document.createElement('div');host.className='enhanced-control';host.dataset.control=name;
 let hidden;if(!isText){hidden=document.createElement('input');hidden.type='hidden';hidden.name=name;hidden.value=model.value;hidden.dataset.enhanced=name;control.replaceWith(hidden,host);enhancedControlModels.set(hidden,model)}else control.replaceWith(host);
 const update=value=>{model.value=value??'';if(hidden){hidden.value=model.value;hidden.dispatchEvent(new Event('change',{bubbles:true}))}};
 const app=createApp({render(){const props={modelValue:model.value,'onUpdate:modelValue':update,style:{width:'100%'}};return h(ElConfigProvider,{locale:zhCn},{default:()=>isSelect?h(ElSelect,{...props,filterable:creatable||options.length>7,allowCreate:creatable,defaultFirstOption:creatable,clearable:!control.required,placeholder:creatable?'选择或输入供应商':'请选择'},()=>options.map(x=>h(ElOption,{key:x.value,label:x.label,value:x.value,disabled:x.disabled}))):isDate?h(ElDatePicker,{...props,type:'date',valueFormat:'YYYY-MM-DD',placeholder:'选择日期',disabledDate:min?(d=>d.toISOString().slice(0,10)<min):undefined}):h(ElInput,{...props,name,type:control.tagName==='TEXTAREA'?'textarea':control.type,rows:control.tagName==='TEXTAREA'?3:undefined,readonly:control.readOnly,disabled:control.disabled,placeholder:control.placeholder||'',maxlength:control.maxLength>0?control.maxLength:undefined})})}});app.mount(host);modalControlApps.push(app)
 }}
function setEnhancedValue(form,name,value){let hidden=form.querySelector(`input[type="hidden"][data-enhanced="${name}"]`);if(!hidden)return;hidden.value=value;let model=enhancedControlModels.get(hidden);if(model)model.value=value}
const filterControlApps=[];
function enhanceFilterControls(){for(const app of filterControlApps.splice(0))app.unmount();const content=document.querySelector('.content');if(!content)return;for(const control of [...content.querySelectorAll('select[data-filter],input[type="date"][data-filter]')]){const isSelect=control.tagName==='SELECT',name=control.dataset.filter,value=control.value,options=isSelect?[...control.options].map(x=>({value:x.value,label:x.textContent})):[],host=document.createElement('div');host.className='enhanced-filter';host.dataset.filterControl=name;control.replaceWith(host);const app=createApp({render(){const props={modelValue:draftFilter[name]??filter[name]??value,'onUpdate:modelValue':next=>{draftFilter[name]=next||''},clearable:true};return h(ElConfigProvider,{locale:zhCn},{default:()=>isSelect?h(ElSelect,{...props,placeholder:'全部',style:{width:'100%'}},()=>options.map(x=>h(ElOption,{key:x.value,label:x.label,value:x.value}))):h(ElDatePicker,{...props,type:'date',valueFormat:'YYYY-MM-DD',placeholder:name==='recFrom'?'开始日期':'结束日期',style:{width:'100%'}})})}});app.mount(host);filterControlApps.push(app)}}
function enhanceTablePagination(){const content=document.querySelector('.content');if(!content)return;for(const wrap of content.querySelectorAll('.table-wrap')){if(wrap.dataset.paginated)return;wrap.dataset.paginated='true';const rows=[...wrap.querySelectorAll('tbody>tr')],empty=rows.length===1&&rows[0].querySelector('.empty'),total=empty?0:rows.length,pageSize=10;if(total<=pageSize)continue;const pages=Math.ceil(total/pageSize);let current=1;const pager=document.createElement('div');pager.className='table-pagination';wrap.insertAdjacentElement('afterend',pager);const render=()=>{rows.forEach((row,index)=>row.hidden=index<(current-1)*pageSize||index>=current*pageSize);const nums=Array.from({length:pages},(_,i)=>i+1).map(n=>`<button type="button" class="page-number ${n===current?'active':''}" data-number="${n}">${n}</button>`).join('');pager.innerHTML=`<span>共 ${total} 条 · 每页 10 条</span><div><button type="button" data-step="prev" ${current===1?'disabled':''}>上一页</button>${nums}<button type="button" data-step="next" ${current===pages?'disabled':''}>下一页</button></div>`};pager.addEventListener('click',event=>{const button=event.target.closest('button');if(!button||button.disabled)return;if(button.dataset.number)current=Number(button.dataset.number);else current+=button.dataset.step==='next'?1:-1;current=Math.max(1,Math.min(pages,current));render()});render()}}
function showModal(title,body,submit='',kind='',wide=false){closeModal();body=body.replace(/(<label class="field(?: full)?">)([^<]*?)\s*\*/g,(_,start,label)=>start+fieldLabel(label+' *'));modalShellApp=createApp({render(){return h(ElDialog,{modelValue:true,title,width:wide?'760px':'600px',class:'business-dialog',appendTo:'#modalRoot',closeOnClickModal:false,'onUpdate:modelValue':value=>{if(!value)closeModal()}},{default:()=>h('form',{id:'dialogForm','data-kind':kind,onSubmit:event=>{event.preventDefault();submitDialog(event.target)}},h('div',{class:'modal-body',innerHTML:body})),footer:()=>h('div',{class:'dialog-actions'},[h(ElButton,{onClick:closeModal},()=> '取消'),submit?h(ElButton,{type:'primary',onClick:()=>{let form=document.querySelector('#dialogForm');if(form)submitDialog(form)}},()=>submit):null])})}});modalShellApp.mount('#modalRoot');nextTick(()=>enhanceDialogControls())}
function closeModal(){for(const app of modalControlApps.splice(0))app.unmount();if(modalShellApp){modalShellApp.unmount();modalShellApp=null}document.querySelector('#modalRoot').innerHTML=''}
function fail(msg){toast(msg,'error');return false}
function positiveInt(value){return Number.isSafeInteger(Number(value))&&Number(value)>0}
function returnedQty(issueId){return state.movements.filter(m=>m.type==='退货入库'&&m.issueId===issueId).reduce((n,m)=>n+m.qty,0)}
function addMovement(it,qty,type,reason,details={}){
 if(!Number.isSafeInteger(qty)||!qty)throw Error('变动数量必须为非零整数');
 if(it.stock+qty<0)throw Error('库存不足，无法完成操作');
 if(qty<0){let lots=state.batches.filter(b=>b.itemId===it.id&&b.qty>0).sort((a,b)=>(a.expiry||'9999-12-31').localeCompare(b.expiry||'9999-12-31')||a.receivedAt.localeCompare(b.receivedAt));if(lots.reduce((n,b)=>n+b.qty,0)<-qty)throw Error('可用批次库存不足');let remaining=-qty;for(const lot of lots){let used=Math.min(remaining,lot.qty);lot.qty-=used;remaining-=used;if(!remaining)break}}
 else state.batches.push({id:uid('LOT'),itemId:it.id,qty,code:details.batch||uid('B'),expiry:details.expiry||'',supplier:details.supplier||'',receivedAt:date()});
 it.stock+=qty;if(details.price>0)it.price=Number(details.price);
 it.expiry=state.batches.filter(b=>b.itemId===it.id&&b.qty>0&&b.expiry).map(b=>b.expiry).sort()[0]||'';
 state.movements.push({id:uid(qty>0?'RK':'CK'),itemId:it.id,type,qty,price:Number(details.price||it.price||0),supplier:details.supplier||'',batch:details.batch||'',operator:user().name,reason,time:now().slice(0,16).replace('T',' '),dept:details.dept||user().dept,taskId:details.taskId||'',issueId:details.issueId||''})
}
function itemForm(id){const it=id?item(id):{},stock=it?.stock||0,reserved=id?locked(id):0,unit=E(it?.unit||'');showModal(id?'编辑物品':'新增物品',`<div class="item-stock-summary"><div><span>当前库存</span><strong>${fmt(stock)} <small>${unit}</small></strong></div><div><span>可用库存</span><strong>${fmt(stock-reserved)} <small>${unit}</small></strong></div><div><span>锁定库存</span><strong>${fmt(reserved)} <small>${unit}</small></strong></div></div><div class="form-grid">${input('物品名称 *','name','text',it.name||'','required maxlength="40"')}${input('物品编码 *','code','text',it.code||'','required maxlength="30"')}${input('条形码','barcode','text',it.barcode||'')}${select('分类 *','category',dictOptions('categories',it.category),it.category||state.dictionaries.categories[0])}${input('规格 *','spec','text',it.spec||'','required')}${select('单位 *','unit',dictOptions('units',it.unit),it.unit||state.dictionaries.units[0])}${select('库存位置 *','location',dictOptions('locations',it.location),it.location||state.dictionaries.locations[0])}${input('安全库存 *','safety','number',it.safety??10,'required min="0" step="1"')}</div><p class="hint section">库存由入库与出库记录自动计算；分类、单位和库位请在基础字典中维护。</p>`,'保存物品',`item:${id||''}`)}
const dictionaryGroup=(type,label,values)=>`<section class="dictionary-card" data-dictionary="${type}"><div class="dictionary-card-head"><b>${label}</b><span>${values.length} 项</span></div><div class="dictionary-tags">${values.map(value=>`<span class="dictionary-tag"><input type="hidden" name="${type}" value="${E(value)}"><span>${E(value)}</span><button type="button" data-remove-dict aria-label="删除 ${E(value)}">×</button></span>`).join('')}</div><div class="dictionary-add"><input type="text" data-native placeholder="输入新${label}"><button type="button" data-add-dict="${type}">添加</button></div></section>`;
function dictionaryForm(){showModal('基础字典维护',`<div class="dictionary-note">统一维护物品档案可选项；正在使用的内容无法删除。</div><div class="dictionary-grid">${dictionaryGroup('categories','物品分类',state.dictionaries.categories)}${dictionaryGroup('units','计量单位',state.dictionaries.units)}${dictionaryGroup('locations','库存位置',state.dictionaries.locations)}</div>`,'保存字典','dictionaries',true)}
function batchDetail(id){const it=item(id),lots=state.batches.filter(x=>x.itemId===id).slice().sort((a,b)=>(a.expiry||'9999-12-31').localeCompare(b.expiry||'9999-12-31')),expiryCell=lot=>{if(lot.qty<=0)return badge('已耗尽','neutral');if(!lot.expiry)return badge('长期有效','neutral');const expired=lot.expiry<date(),soon=!expired&&lot.expiry<=days(30);return`<span class="batch-expiry"><b>${E(lot.expiry)}</b>${badge(expired?'已过期':soon?'即将过期':'有效',expired?'danger':soon?'warning':'')}</span>`};showModal(`${it.name} · 批次库存`,`<div class="batch-summary"><span><small>当前库存</small><b>${it.stock} ${E(it.unit)}</b></span><span><small>在库批次</small><b>${lots.filter(x=>x.qty>0).length} 个</b></span></div>${table(['批次号','剩余数量','供应商','入库日期','批次效期'],lots.map(l=>row([`<strong>${E(l.code)}</strong>`,`<strong>${l.qty}</strong> ${E(it.unit)}`,E(l.supplier||'—'),E(l.receivedAt||'—'),expiryCell(l)])),'暂无批次记录')}`,'','',true)}
function inboundDetail(id){const movement=state.movements.find(x=>x.id===id),current=item(movement?.itemId);if(!movement||!current)return fail('入库记录不存在');const relation=movement.taskId?`采购任务 ${movement.taskId}`:movement.issueId?`领用单 ${movement.issueId}`:'独立入库',detail=(label,value)=>`<div><span>${label}</span><b>${value}</b></div>`;showModal('入库详情',`<div class="inbound-detail-hero"><div class="inbound-detail-icon">${navIcons.inbound}</div><div class="inbound-detail-heading"><span>入库单号</span><strong>${E(movement.id)}</strong><p>${E(movement.time)} · ${E(movement.operator||'—')}</p></div>${badge(movement.type,movement.type==='库存调整'?'blue':'')}</div><div class="inbound-detail-stats"><div><span>入库数量</span><strong>+${fmt(movement.qty)}</strong><small>${E(current.unit)}</small></div><div><span>入库单价</span><strong>${money(movement.price)}</strong><small>/ ${E(current.unit)}</small></div><div class="total"><span>入库金额</span><strong>${money(movement.qty*movement.price)}</strong><small>本次入库合计</small></div></div><div class="inbound-detail-grid"><section><div class="inbound-detail-title"><span class="item-icon">${categoryIcons[current.category]||navIcons.items}</span><div><b>物品信息</b><small>${E(current.name)} · ${E(current.code)}</small></div></div><div class="inbound-detail-list">${detail('物品规格',E(current.spec||'—'))}${detail('物品分类',E(current.category||'—'))}${detail('库存位置',E(current.location||'—'))}${detail('计量单位',E(current.unit||'—'))}</div></section><section><div class="inbound-detail-title"><span class="item-icon">${navIcons.purchasing}</span><div><b>入库信息</b><small>${E(relation)}</small></div></div><div class="inbound-detail-list">${detail('供应商',E(movement.supplier||'—'))}${detail('批次号',E(movement.batch||'—'))}${detail('所属部门',E(movement.dept||'—'))}${detail('关联业务',E(relation))}</div></section></div><div class="inbound-detail-reason"><span>入库原因</span><p>${E(movement.reason||'—')}</p></div>`,'','',true)}
function outboundDetail(id){const issue=state.issues.find(x=>x.id===id),current=item(issue?.itemId),movement=state.movements.find(x=>x.issueId===id&&x.type==='领用出库');if(!issue||!current||!movement)return fail('出库记录不存在');const returned=returnedQty(id),detail=(label,value)=>`<div><span>${label}</span><b>${value}</b></div>`;showModal('出库详情',`<div class="inbound-detail-hero outbound-detail-hero"><div class="inbound-detail-icon">${navIcons.issues}</div><div class="inbound-detail-heading"><span>出库单号</span><strong>${E(movement.id)}</strong><p>${E(movement.time)} · ${E(movement.operator||'—')}</p></div>${badge('已出库','warning')}</div><div class="inbound-detail-stats outbound-detail-stats"><div><span>出库数量</span><strong>-${fmt(issue.qty)}</strong><small>${E(current.unit)}</small></div><div><span>已退回数量</span><strong>${fmt(returned)}</strong><small>${E(current.unit)}</small></div><div class="total"><span>实际领用</span><strong>${fmt(issue.qty-returned)}</strong><small>${E(current.unit)}</small></div></div><div class="inbound-detail-grid"><section><div class="inbound-detail-title"><span class="item-icon">${categoryIcons[current.category]||navIcons.items}</span><div><b>物品信息</b><small>${E(current.name)} · ${E(current.code)}</small></div></div><div class="inbound-detail-list">${detail('物品规格',E(current.spec||'—'))}${detail('物品分类',E(current.category||'—'))}${detail('库存位置',E(current.location||'—'))}${detail('计量单位',E(current.unit||'—'))}</div></section><section><div class="inbound-detail-title"><span class="item-icon">${navIcons.issues}</span><div><b>领用信息</b><small>${E(issue.id)}</small></div></div><div class="inbound-detail-list">${detail('领用人',E(issue.requester||'—'))}${detail('所属部门',E(issue.dept||'—'))}${detail('申请日期',E(issue.created||'—'))}${detail('出库操作人',E(movement.operator||'—'))}</div></section></div><div class="inbound-detail-reason outbound-detail-reason"><span>领用用途</span><p>${E(issue.purpose||'—')}</p></div>`,'','',true)}
function inboundForm(defaultIssueId=''){const returnOptions=[['','请选择已出库领用单'],...state.issues.filter(x=>x.status==='completed'&&x.qty>returnedQty(x.id)).map(x=>[x.id,`${x.id} · ${item(x.itemId)?.name} · ${x.requester} · 可退 ${x.qty-returnedQty(x.id)}`])];showModal('新增入库 / 库存调整',`<div class="form-grid">${select('业务类型 *','type',[['采购入库','采购入库'],['退货入库','退货入库'],['库存调整','库存调整']])}${select('物品 *','itemId',itemOptions(false))}<div class="return-link full" hidden>${select('关联原领用单 *','issueId',returnOptions,defaultIssueId)}</div>${input('变动数量 *','qty','number',1,'required step="1" min="-999999"')}${input('单价（元）','price','number',0,'min="0" step="0.01"')}${supplierSelect('供应商（采购入库必填）')}${input('批次号（采购入库必填）','batch')}${input('有效期（按批次预警）','expiry','date')}${input('操作人','operator','text',user().name,'disabled')}<label class="field full">变化原因 *<textarea name="reason" required placeholder="请填写此次入库或调整的原因"></textarea></label></div><p class="hint section">采购入库须填写供应商和批次；退回入库须关联原领用单，且不能超过未退回数量。</p>`,'确认入库 / 调整','inbound');if(defaultIssueId)nextTick(()=>{let form=document.querySelector('#dialogForm');setEnhancedValue(form,'type','退货入库');syncInboundType(form)})}
function syncInboundType(form){let type=form.querySelector('[name="type"]')?.value,group=form.querySelector('.return-link'),issueId=form.querySelector('[name="issueId"]')?.value;if(!group)return;group.hidden=type!=='退货入库';if(type==='退货入库'&&issueId){let issue=state.issues.find(x=>x.id===issueId);if(issue)setEnhancedValue(form,'itemId',issue.itemId)}}
function issueForm(){showModal('发起领用申请',`<div class="form-grid">${select('领用物品 *','itemId',itemOptions())}${input('数量 *','qty','number',1,'required min="1" step="1"')}${input('领用人 *','requester','text',user().name,'required readonly')}${select('所属部门 *','dept',departmentOptions(),user().dept)}<label class="field full">领用用途 *<textarea name="purpose" required></textarea></label></div><p class="hint section">停用物品不可领用，出库数量不能超过当前可用库存。</p>`,'提交申请','issue')}
function lineHTML(it='',qty=1){return `<div class="line-item">${select('采购物品 *','itemId',itemOptions(),it)}${input('数量 *','qty','number',qty,'min="1" step="1" required')}<button type="button" class="remove" data-remove-line title="移除该物品">×</button></div>`}
function requestForm(id='',preferred=''){const req=id?state.requests.find(x=>x.id===id):null;showModal(req?'编辑采购申请':'新建采购申请',`<div class="request-line-head"><span>${fieldLabel('采购物品 *')}</span><span>${fieldLabel('数量 *')}</span><span></span></div><div id="requestLines">${(req?.lines||[{itemId:preferred||state.items.find(x=>x.active)?.id,qty:1}]).map(x=>lineHTML(x.itemId,x.qty)).join('')}</div><button type="button" class="button small" data-add-line>＋ 添加物品</button><div class="form-grid section">${input('期望到货日期 *','expected','date',req?.expected||days(7),`required min="${date()}"`)}${select('申请部门 *','dept',departmentOptions(),req?.dept||user().dept)}<label class="field full">采购用途 *<textarea name="purpose" required>${E(req?.purpose||'')}</textarea></label></div><p class="hint section">保存草稿后可再次编辑；提交后需审批通过才会产生采购任务。</p>`,'保存草稿','request:'+id,true)}
function taskForm(id){const t=state.tasks.find(x=>x.id===id);if(!t||t.received>0||['partial','completed'].includes(t.status))return fail('任务已有到货记录，采购报价已锁定，不能再修改');const it=item(t.itemId),remaining=t.qty-t.received,statusOptions=t.status==='ordered'?[['ordered','采购中']]:[['pending','待采购'],['ordered','采购中']];showModal(t.status==='ordered'?'调整采购信息':'完善采购信息',`<div class="purchase-task-summary"><span class="purchase-task-icon">${categoryIcons[it?.category]||navIcons.items}</span><div><small>采购物品</small><b>${E(it?.name||'—')}</b></div><div><small>采购数量</small><b>${t.qty} ${E(it?.unit||'')}</b></div><div><small>待到货</small><b>${remaining} ${E(it?.unit||'')}</b></div></div><div class="form-grid purchase-task-form">${supplierSelect('供应商 *',t.supplier)}${input('采购单价（元）*','price','number',t.price||'','required min="0.01" step="0.01" placeholder="请输入采购单价"')}${input('预计到货日期 *','eta','date',t.eta||days(5),'required')}${select('采购状态 *','status',statusOptions,t.status)}</div><div class="purchase-task-note"><span>说明</span>${t.status==='ordered'?'采购已确认，状态不可退回；首次到货后供应商与采购单价将锁定。':'将状态设为“采购中”后才可以登记到货。'}</div>`,'保存采购信息','task:'+id)}
function receiveForm(id){const t=state.tasks.find(x=>x.id===id);if(!t?.supplier||!t.price||!t.eta||t.status==='pending')return fail('请先完善采购信息，并将采购状态设为“采购中”');const it=item(t.itemId),remaining=t.qty-t.received;showModal('登记实际到货',`<div class="arrival-summary"><div class="arrival-item"><span class="purchase-task-icon">${categoryIcons[it?.category]||navIcons.items}</span><span><small>采购物品</small><b>${E(it?.name||'—')}</b></span></div><div><small>采购数量</small><b>${t.qty} ${E(it?.unit||'')}</b></div><div><small>已到货</small><b>${t.received} ${E(it?.unit||'')}</b></div><div class="arrival-remaining"><small>本次最多可收</small><b>${remaining} ${E(it?.unit||'')}</b></div></div><div class="arrival-contract"><div><small>供应商</small><b>${E(t.supplier)}</b></div><div><small>采购单价</small><b>${money(t.price)} / ${E(it?.unit||'件')}</b></div><div><small>预计到货</small><b>${E(t.eta)}</b></div></div><div class="arrival-section-title"><b>本次到货信息</b><span>实际入库数量将直接增加库存</span></div><div class="form-grid arrival-task-form">${input('本次到货数量 *','qty','number',remaining,`required min="1" max="${remaining}" step="1" placeholder="最多 ${remaining}"`)}${input('到货批次 *','batch','text',uid('B'),'required placeholder="请输入到货批次"')}${input('有效期','expiry','date')}</div>`,'确认入库','receive:'+id,true)}
function requestDetail(id){const x=state.requests.find(y=>y.id===id),saved=state.audits.filter(log=>log.requestId===id),fallback=[{action:'创建申请',operator:x.requester,role:'申请人',time:`${x.created} 09:00`,detail:`由${x.dept}发起采购申请`},...x.status!=='draft'?[{action:({submitted:'提交审批',approved:'审批通过',rejected:'审批驳回',completed:'采购完成'})[x.status]||'状态更新',operator:x.approver||x.requester,role:x.approver?'审批人':'申请人',time:`${x.created} 10:00`,detail:x.rejectReason||`当前状态：${requestStatusBadge(x).replace(/<[^>]+>/g,'')}`}]:[]],logs=(saved.length?saved:fallback).slice().reverse();const lineRows=x.lines.map(line=>{const current=item(line.itemId);return`<div class="request-detail-line"><span class="item-icon">${categoryIcons[current?.category]||navIcons.items}</span><span><b>${E(current?.name||'物品已删除')}</b><small>${E(current?.code||'—')} · ${E(current?.spec||'—')}</small></span><strong>${line.qty} ${E(current?.unit||'')}</strong></div>`}).join('');showModal('采购申请详情',`<div class="request-detail-hero"><div><span>申请编号</span><strong>${E(x.id)}</strong><p>${E(x.purpose)}</p></div>${requestStatusBadge(x)}</div><div class="request-detail-meta"><div><span>申请人</span><b>${E(x.requester)}</b></div><div><span>申请部门</span><b>${E(x.dept)}</b></div><div><span>期望到货</span><b>${E(x.expected)}</b></div><div><span>审批人</span><b>${E(x.approver||'—')}</b></div></div>${x.rejectReason?`<div class="request-reject-reason"><span>驳回原因</span>${E(x.rejectReason)}</div>`:''}<div class="request-detail-columns"><section><div class="request-section-head"><b>采购物品</b><span>${x.lines.length} 项</span></div><div class="request-detail-lines">${lineRows}</div></section><section><div class="request-section-head"><b>操作记录</b><span>${logs.length} 条</span></div><div class="audit-timeline request-audits">${logs.map(log=>`<div><i></i><span><b>${E(log.action)}</b><small>${E(log.operator)} · ${E(log.role)}</small><p>${E(log.time)}${log.detail?' · '+E(log.detail):''}</p></span></div>`).join('')}</div></section></div>`,'','',true)}
function taskHistory(id){let arr=state.movements.filter(m=>m.taskId===id);showModal('关联入库记录',table(['入库单号','时间','到货数量','供应商 / 批次'],arr.map(m=>row([E(m.id),E(m.time),`+${m.qty}`,`${E(m.supplier)} / ${E(m.batch)}`]))),'','',true)}

function exportRecords(){const q=(filter.recQ||'').toLowerCase(),person=(filter.personQ||'').toLowerCase(),dept=filter.recDept||'',cat=filter.recCat||'',typ=filter.recType||'',from=filter.recFrom||'',to=filter.recTo||'',detail=recordsTab.value==='issues';const arr=detail?state.issues.filter(x=>x.status==='completed'&&(!dept||x.dept===dept)&&x.requester.toLowerCase().includes(person)&&(!from||(x.completed||x.created)>=from)&&(!to||(x.completed||x.created)<=to)):state.movements.filter(m=>{let it=item(m.itemId);return(it?.name||'').toLowerCase().includes(q)&&(!dept||m.dept===dept)&&(!cat||it?.category===cat)&&(!typ||m.type===typ)&&(!from||m.time.slice(0,10)>=from)&&(!to||m.time.slice(0,10)<=to)});const fields=detail?['领用单号','领用人','部门','物品编码','物品名称','数量','单位','用途','出库日期']:['单号','时间','物品编码','物品名称','分类','操作类型','变动数量','单位','单价','操作人','部门','变化原因'];const quote=(x)=>`"${String(x??'').replaceAll('"','""')}"`;const rows=detail?arr.map(x=>[x.id,x.requester,x.dept,item(x.itemId)?.code,item(x.itemId)?.name,x.qty,item(x.itemId)?.unit,x.purpose,x.completed||x.created]):arr.map(m=>[m.id,m.time,item(m.itemId)?.code,item(m.itemId)?.name,item(m.itemId)?.category,m.type,m.qty,item(m.itemId)?.unit,m.price,m.operator,m.dept,m.reason]);const csv='\ufeff'+[fields,...rows].map(line=>line.map(quote).join(',')).join('\r\n');const link=document.createElement('a'),url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));link.href=url;link.download=`好财-${detail?'领用明细':'库存流水'}-${date()}.csv`;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);toast(`已导出 ${arr.length} 条${detail?'领用明细':'库存流水'}`)}

function act(action){if(!canAction(action))return fail(permissionMessage(action));let [type,id]=action.split(':');let x,it;switch(type){
case 'recordTab':Object.keys(draftFilter).forEach(k=>delete draftFilter[k]);recordsTab.value=id==='issues'?'issues':'movements';return;
case 'searchFilters':Object.assign(filter,draftFilter);toast('已应用筛选条件');return;
case 'clearFilters':Object.keys(draftFilter).forEach(k=>delete draftFilter[k]);Object.keys(filter).forEach(k=>delete filter[k]);toast('筛选条件已重置');return;
case 'exportRecords':return exportRecords();
case 'newItem':return itemForm();case 'editItem':return itemForm(id);case 'manageDictionaries':return dictionaryForm();case 'itemBatches':return batchDetail(id);
case 'inboundDetail':return inboundDetail(id);
case 'outboundDetail':return outboundDetail(id);
case 'toggleItem':it=item(id);if(it){it.active=!it.active;toast(it.active?'物品已启用':'物品已停用')}return;
case 'newInbound':return inboundForm();case 'returnIssue':return inboundForm(id);case 'newIssue':return issueForm();case 'newRequest':return requestForm();case 'editRequest':return requestForm(id);
case 'purchaseFor':page.value='requests';return requestForm('',id);
case 'goTask':x=state.tasks.find(task=>task.id===id);if(!x)return fail('关联采购任务不存在');Object.keys(draftFilter).forEach(key=>delete draftFilter[key]);filter.taskQ=x.id;filter.taskStatus='';page.value='purchasing';window.scrollTo(0,0);toast(`已定位采购任务 ${x.id}`);return;
case 'goPurchase':Object.keys(draftFilter).forEach(key=>delete draftFilter[key]);filter.taskQ=id;filter.taskStatus='';page.value='purchasing';window.scrollTo(0,0);return;
case 'approveIssue':x=state.issues.find(y=>y.id===id);it=item(x.itemId);if(x.status!=='pending')return fail('申请状态已变化');if(!it.active||available(it)<x.qty)return fail('物品已停用或可用库存不足，无法审核通过');x.status='approved';x.operator=user().name;toast('审核通过，数量已锁定，等待执行出库');return;
case 'rejectIssue':x=state.issues.find(y=>y.id===id);if(x.status!=='pending'&&x.status!=='approved')return fail('当前状态不可驳回');x.status='rejected';x.operator=user().name;toast('已驳回领用申请');return;
case 'outIssue':x=state.issues.find(y=>y.id===id);it=item(x.itemId);if(x.status!=='approved'||it.stock<x.qty)return fail('库存不足或申请状态已变化');addMovement(it,-x.qty,'领用出库',`${x.purpose} · ${x.requester}`,{dept:x.dept});x.status='completed';x.operator=user().name;x.completed=date();toast('出库成功，库存流水已记录');return;
case 'submitRequest':x=state.requests.find(y=>y.id===id);if(!['draft','rejected'].includes(x.status))return fail('当前申请不可提交');if(x.lines.some(l=>!item(l.itemId)?.active))return fail('包含已停用物品，请先编辑申请');x.status='submitted';x.rejectReason='';addAudit(x.id,'提交审批',`提交至${x.dept}负责人`);toast('采购申请已提交审批');return;
case 'approveRequest':x=state.requests.find(y=>y.id===id);if(x.status!=='submitted')return fail('仅待审批申请可审批');if(x.lines.some(l=>!item(l.itemId)?.active))return fail('包含已停用物品，不能审批');x.status='approved';x.approver=user().name;x.lines.forEach(l=>state.tasks.push({id:uid('PC'),requestId:x.id,itemId:l.itemId,qty:l.qty,received:0,supplier:'',price:0,eta:'',status:'pending'}));addAudit(x.id,'审批通过',`生成 ${x.lines.length} 条采购任务`);toast(`审批通过，已生成 ${x.lines.length} 条采购任务`);return;
case 'rejectRequest':x=state.requests.find(y=>y.id===id);if(x.status!=='submitted')return fail('仅待审批申请可驳回');ElMessageBox.prompt('请填写驳回原因，申请人修改后可重新提交。','驳回采购申请',{confirmButtonText:'确认驳回',cancelButtonText:'取消',inputPlaceholder:'请输入具体原因',inputValidator:value=>value?.trim()?true:'驳回原因不能为空',type:'warning'}).then(({value})=>{x.rejectReason=value.trim();x.status='rejected';x.approver=user().name;addAudit(x.id,'审批驳回',x.rejectReason);toast('采购申请已驳回')}).catch(()=>{});return;
case 'viewRequest':return requestDetail(id);case 'editTask':return taskForm(id);case 'receiveTask':return receiveForm(id);case 'taskMovements':return taskHistory(id);
}}
function submitDialog(form){runWithLoading(()=>submitDialogNow(form),document.querySelector('.business-dialog')||document.body)}
function submitDialogNow(form){let kind=form.dataset.kind,[type,id]=kind.split(':'),f=new FormData(form),v=(k)=>String(f.get(k)||'').trim();let x,it,n;if(type==='item'&&!canAction(id?`editItem:${id}`:'newItem'))return fail(permissionMessage('newItem'));if(type==='inbound'&&!canAction('newInbound'))return fail(permissionMessage('newInbound'));if(type==='issue'&&!canAction('newIssue'))return fail(permissionMessage('newIssue'));if(['task','receive'].includes(type)&&!canAction(`editTask:${id}`))return fail(permissionMessage('editTask'));if(type==='request'&&!canAction(id?`editRequest:${id}`:'newRequest'))return fail(permissionMessage('newRequest'));
try{switch(type){
case 'dictionaries':{const parse=name=>[...new Set(f.getAll(name).map(value=>String(value).trim()).filter(Boolean))],categories=parse('categories'),units=parse('units'),locations=parse('locations');if(!categories.length||!units.length||!locations.length)return fail('分类、单位和库存位置均至少保留一项');const missing=state.items.find(current=>!categories.includes(current.category)||!units.includes(current.unit)||!locations.includes(current.location));if(missing)return fail(`“${missing.name}”正在使用被删除的字典值，请先修改物品档案`);state.dictionaries={categories,units,locations};toast('基础字典已更新');break}
case 'item':{let name=v('name'),code=v('code'),barcode=v('barcode'),safety=Number(v('safety'));if(!name||!code||!v('category')||!v('spec')||!v('unit')||!v('location')||!Number.isSafeInteger(safety)||safety<0)return fail('请填写完整物品信息和有效安全库存');if(state.items.some(y=>y.id!==id&&(y.code===code||(barcode&&y.barcode===barcode))))return fail('物品编码或条形码已存在');let data={name,code,barcode,category:v('category'),spec:v('spec'),unit:v('unit'),location:v('location'),safety};if(id)Object.assign(item(id),data);else state.items.push({id:uid('I'),...data,stock:0,price:0,active:true,expiry:''});toast(id?'物品已更新':'物品已创建');break}
case 'inbound':{let inboundType=v('type'),linked=state.issues.find(x=>x.id===v('issueId'));it=inboundType==='退货入库'?item(linked?.itemId):item(v('itemId'));n=Number(v('qty'));let price=Number(v('price'));if(!it||!Number.isSafeInteger(n)||n===0||((inboundType!=='库存调整')&&n<0))return fail('请选择物品并填写有效数量');if(n<0&&-n>available(it))return fail('调整出库不可超过可用库存');if(!v('reason'))return fail('请填写变化原因');if(!Number.isFinite(price)||price<0)return fail('请填写有效单价');if(inboundType==='采购入库'&&(!v('supplier')||!v('batch')||price<=0))return fail('采购入库必须填写供应商、批次及有效单价');if(inboundType==='退货入库'&&(!linked||linked.status!=='completed'||!positiveInt(n)||n>linked.qty-returnedQty(linked.id)))return fail('请关联已出库领用单，且退回数量不能超过未退回数量');let supplier=inboundType==='退货入库'?linked.requester:inboundType==='库存调整'?'内部盘点':v('supplier'),batch=inboundType==='退货入库'?`RET-${linked.id}`:inboundType==='库存调整'?(v('batch')||uid('ADJ')):v('batch');addMovement(it,n,inboundType,inboundType==='退货入库'?`${v('reason')} · 关联 ${linked.id}`:v('reason'),{price,supplier,batch,expiry:v('expiry'),issueId:linked?.id||'',dept:linked?.dept||user().dept});if(inboundType==='采购入库')rememberSupplier(supplier);toast('库存已更新，变动记录已保存');break}
case 'issue':{it=item(v('itemId'));n=Number(v('qty'));if(!it?.active)return fail('已停用物品不可申请领用');if(!positiveInt(n)||n>available(it))return fail(`领用数量不能超过可用库存（${available(it)}）`);if(v('requester')!==user().name||!departments.includes(v('dept'))||!v('purpose'))return fail('请确认领用人、选择有效部门并填写用途');state.issues.push({id:uid('LY'),itemId:it.id,qty:n,requester:user().name,dept:v('dept'),purpose:v('purpose'),status:'pending',created:date()});toast('领用申请已提交');break}
case 'request':{let lines=[...form.querySelectorAll('.line-item')].map(el=>({itemId:el.querySelector('[name="itemId"]').value,qty:Number(el.querySelector('[name="qty"]').value)}));if(!lines.length||lines.some(l=>!item(l.itemId)?.active||!positiveInt(l.qty)))return fail('请至少添加一种有效物品，并填写正整数数量');if(new Set(lines.map(l=>l.itemId)).size!==lines.length)return fail('同一物品请合并为一行');if(!v('expected')||v('expected')<date()||!v('purpose')||!departments.includes(v('dept')))return fail('请填写用途、有效到货日期并选择申请部门');if(id){x=state.requests.find(y=>y.id===id);if(!['draft','rejected'].includes(x.status))return fail('当前状态不可编辑');Object.assign(x,{lines,expected:v('expected'),purpose:v('purpose'),dept:v('dept'),status:'draft'});addAudit(x.id,'修改草稿','更新采购物品、数量或申请信息')}else{x={id:uid('CG'),lines,expected:v('expected'),purpose:v('purpose'),dept:v('dept'),requester:user().name,status:'draft',created:date()};state.requests.push(x);addAudit(x.id,'创建申请','保存采购申请草稿')}toast('采购申请草稿已保存，可在列表中提交');break}
case 'task':{x=state.tasks.find(y=>y.id===id);n=Number(v('price'));if(!x||x.received>0||['partial','completed'].includes(x.status))return fail('任务已有到货记录，采购报价已锁定，不能再修改');if(x.status==='ordered'&&v('status')!=='ordered')return fail('采购已确认，不能退回待采购状态');if(!['pending','ordered'].includes(v('status'))||!v('supplier')||!v('eta')||!Number.isFinite(n)||n<=0)return fail('请填写供应商、价格、预计到货日期和有效采购状态');Object.assign(x,{supplier:v('supplier'),price:n,eta:v('eta'),status:v('status')});rememberSupplier(v('supplier'));addAudit(x.requestId,x.status==='ordered'?'确认采购':'更新采购信息',`${item(x.itemId)?.name} · ${v('supplier')} · ${money(n)}`);toast(x.status==='ordered'?'采购已确认，可以登记到货':'采购信息已保存');break}
case 'receive':{x=state.tasks.find(y=>y.id===id);if(!x?.supplier||!x.price||!x.eta||x.status==='pending')return fail('采购信息尚未完善，不能登记到货');it=item(x.itemId);n=Number(v('qty'));if(!positiveInt(n)||n>x.qty-x.received)return fail('到货数量不能超过未到货数量');if(!v('batch'))return fail('请填写到货批次');addMovement(it,n,'采购入库',`采购任务 ${x.id} 分批到货`,{supplier:x.supplier,batch:v('batch'),price:x.price,expiry:v('expiry'),taskId:id});x.received+=n;x.status=x.received===x.qty?'completed':'partial';let req=state.requests.find(y=>y.id===x.requestId);if(req&&state.tasks.filter(y=>y.requestId===req.id).every(y=>y.status==='completed'))req.status='completed';addAudit(x.requestId,x.status==='completed'?'采购到货完成':'采购部分到货',`${it.name} 本次到货 ${n} ${it.unit}，累计 ${x.received}/${x.qty}`);toast(x.status==='completed'?'全部到货，采购申请已完成':'部分到货已入库，剩余数量待处理');break}
default:return fail('未知表单操作')}
closeModal();return true}catch(e){return fail(e.message||'操作失败')}}

document.querySelector('#modalRoot').addEventListener('click',e=>{if(e.target.matches('[data-close]')||e.target.classList.contains('modal-backdrop'))closeModal();if(e.target.closest('[data-add-line]')){let lines=document.querySelector('#requestLines');lines?.insertAdjacentHTML('beforeend',lineHTML());enhanceDialogControls(lines?.lastElementChild)}if(e.target.closest('[data-remove-line]')){let rows=document.querySelectorAll('.line-item');if(rows.length>1)e.target.closest('.line-item').remove();else toast('至少保留一项物品')}});
document.querySelector('#modalRoot').addEventListener('click',e=>{const add=e.target.closest('[data-add-dict]'),remove=e.target.closest('[data-remove-dict]');if(add){const card=add.closest('.dictionary-card'),input=card.querySelector('[data-native]'),value=input.value.trim(),name=add.dataset.addDict;if(!value)return fail('请输入要添加的内容');if([...card.querySelectorAll(`input[name="${name}"]`)].some(item=>item.value===value))return fail('该选项已存在');card.querySelector('.dictionary-tags').insertAdjacentHTML('beforeend',`<span class="dictionary-tag"><input type="hidden" name="${name}" value="${E(value)}"><span>${E(value)}</span><button type="button" data-remove-dict aria-label="删除 ${E(value)}">×</button></span>`);input.value='';card.querySelector('.dictionary-card-head span').textContent=`${card.querySelectorAll('.dictionary-tag').length} 项`;input.focus()}if(remove){const card=remove.closest('.dictionary-card');remove.closest('.dictionary-tag').remove();card.querySelector('.dictionary-card-head span').textContent=`${card.querySelectorAll('.dictionary-tag').length} 项`}});
document.querySelector('#modalRoot').addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.matches('[data-native]')){e.preventDefault();e.target.closest('.dictionary-card').querySelector('[data-add-dict]').click()}});
document.querySelector('#modalRoot').addEventListener('change',e=>{let form=e.target.closest('form[data-kind="inbound"]');if(form)syncInboundType(form)});
createApp({setup(){const currentUser=computed(()=>users[state.role]),warningCount=computed(()=>warnings().length),pageHTML=computed(()=>applyPermissions(refineIcons(decorateToolbar(({dashboard,items,inbound,issues,requests,purchasing,alerts,records})[page.value](),page.value)))),themeOpen=ref(false),searchOpen=ref(false),globalQuery=ref('');
watch(pageHTML,()=>nextTick(()=>{enhanceFilterControls();enhanceTablePagination()}),{flush:'post',immediate:true});
const globalResults=computed(()=>{const q=globalQuery.value.trim().toLowerCase();if(!q)return[{type:'nav',id:'items',page:'items',title:'物品档案',subtitle:'浏览全部物品与库存'},{type:'nav',id:'requests',page:'requests',title:'采购申请',subtitle:'创建与审批采购申请'},{type:'nav',id:'records',page:'records',title:'库存记录',subtitle:'查看和导出库存流水'}];return[...state.items.filter(x=>(x.name+x.code+x.barcode).toLowerCase().includes(q)).map(x=>({type:'item',id:x.id,page:'items',title:x.name,subtitle:`物品 · ${x.code} · 库存 ${x.stock}`})),...state.requests.filter(x=>(x.id+x.purpose+x.requester).toLowerCase().includes(q)).map(x=>({type:'request',id:x.id,page:'requests',title:x.id,subtitle:`采购申请 · ${x.requester} · ${x.purpose}`})),...state.tasks.filter(x=>(x.id+x.supplier+(item(x.itemId)?.name||'')).toLowerCase().includes(q)).map(x=>({type:'task',id:x.id,page:'purchasing',title:x.id,subtitle:`采购任务 · ${item(x.itemId)?.name||''}`}))].slice(0,8)});
function go(p){Object.keys(draftFilter).forEach(k=>delete draftFilter[k]);page.value=p;searchOpen.value=false;window.scrollTo(0,0)}function openResult(result){go(result.page);if(result.type==='item')filter.itemsQ=item(result.id)?.name||'';if(result.type==='request')nextTick(()=>requestDetail(result.id));if(result.type==='task'&&canAction(`editTask:${result.id}`))nextTick(()=>state.tasks.find(x=>x.id===result.id)?.status==='completed'?taskHistory(result.id):taskForm(result.id))}function reset(){ElMessageBox.confirm('重置后，当前浏览器中的申请、库存和操作记录都会恢复为初始演示数据。','重置演示数据',{confirmButtonText:'确认重置',cancelButtonText:'取消',type:'warning'}).then(()=>{Object.assign(state,seed());page.value='dashboard';Object.keys(draftFilter).forEach(k=>delete draftFilter[k]);Object.keys(filter).forEach(k=>delete filter[k]);toast('演示数据已重置')}).catch(()=>{})}
watch(searchOpen,opened=>{if(opened){globalQuery.value='';nextTick(()=>document.querySelector('.search-dialog-input input')?.focus())}});
const closeAppearance=(event)=>{if(!event.target.closest('.appearance-wrap'))themeOpen.value=false};const keyHandler=(event)=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='k'){event.preventDefault();searchOpen.value=true}else if(event.key==='Escape'){searchOpen.value=false;themeOpen.value=false}else if(event.key==='/'&&!['INPUT','TEXTAREA'].includes(document.activeElement?.tagName)){event.preventDefault();searchOpen.value=true}};onMounted(()=>{document.addEventListener('click',closeAppearance);document.addEventListener('keydown',keyHandler);nextTick(()=>requestAnimationFrame(()=>document.querySelector('#boot-screen')?.remove()))});onUnmounted(()=>{document.removeEventListener('click',closeAppearance);document.removeEventListener('keydown',keyHandler)});
function onContentClick(e){const target=e.target.closest('[data-action],[data-page]');if(!target)return;if(target.dataset.page)return go(target.dataset.page);const action=target.dataset.action;if(/^(toggleItem|approveIssue|rejectIssue|outIssue|submitRequest|approveRequest|rejectRequest):/.test(action))runWithLoading(()=>act(action),document.querySelector('.content')||document.body);else act(action)}function onFilter(e){const el=e.target;if(el.dataset.filter)draftFilter[el.dataset.filter]=el.value}function onFilterEnter(e){if(e.target.closest('.toolbar')){e.preventDefault();act('searchFilters')}}return{names,users,navIcons,state,page,currentUser,warningCount,pageHTML,go,reset,onContentClick,onFilter,onFilterEnter,appearance,accentOptions,themeOpen,searchOpen,globalQuery,globalResults,openResult}}}).component('ElMenu',ElMenu).component('ElMenuItem',ElMenuItem).component('ElSelect',ElSelect).component('ElOption',ElOption).component('ElButton',ElButton).component('ElDialog',ElDialog).component('ElInput',ElInput).mount('#app');
