import {chromium} from 'playwright-core';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';

const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--no-sandbox','--disable-background-networking','--disable-gpu','--no-first-run']});
const page=await browser.newPage();
const roleLabels={warehouse:'仓库管理员 · 林知远',employee:'普通员工 · 陈小雨',manager:'部门负责人 · 周明（产品部）',managerAdmin:'部门负责人 · 赵岚（行政部）',buyer:'采购人员 · 许安'};
const setRole=async(role)=>{await page.locator('.role-select').click();await page.locator('.el-select-dropdown__item:visible').filter({hasText:roleLabels[role]}).click()};
const selectDialog=async(name,value)=>{const control=page.locator(`#dialogForm [data-enhanced="${name}"] + .enhanced-control`);await control.locator('.el-select').click();await page.locator('.el-select-dropdown__item:visible').filter({hasText:new RegExp(value)}).first().click()};
const setSupplier=async(value)=>{const control=page.locator('#dialogForm [data-enhanced="supplier"] + .enhanced-control .el-select');await control.click();await control.locator('input').fill(value);await control.locator('input').press('Enter')};
const setDate=async(name,value)=>{await page.locator(`#dialogForm [data-enhanced="${name}"]`).evaluate((el,date)=>{el.value=date;el.dispatchEvent(new Event('change',{bubbles:true}))},value)};
const errors=[];page.on('pageerror',error=>errors.push(error.message));
try{
  await page.goto('http://127.0.0.1:5173/',{waitUntil:'domcontentloaded'});
  await page.getByRole('heading',{name:'工作台总览'}).waitFor();
  assert.equal(await page.evaluate(()=>getComputedStyle(document.documentElement).getPropertyValue('--accent').trim()),'#1677ff');
  await page.getByRole('button',{name:/外观/}).click();
  await page.getByRole('button',{name:'☾ 深色'}).click();
  assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
  await page.getByRole('button',{name:'紫罗兰'}).click();
  await page.reload();
  assert.equal(await page.locator('html').getAttribute('data-accent'),'violet');
  await page.getByRole('button',{name:/外观/}).click();
  await page.getByRole('button',{name:'☀ 浅色'}).click();
  await page.getByRole('button',{name:'标准蓝'}).click();
  await page.getByRole('button',{name:'关闭外观设置'}).click();
  await page.keyboard.press('Control+k');
  await page.getByRole('textbox',{name:'全局搜索'}).fill('A4 复印纸');
  await page.getByRole('button',{name:/A4 复印纸/}).first().click();
  await page.getByRole('heading',{name:'物品档案'}).waitFor();
  assert.equal(await page.locator('[data-filter="itemsQ"]').inputValue(),'A4 复印纸');
  await page.locator('[data-action="clearFilters"]').first().click();
  assert.equal(await page.locator('[data-filter="itemsQ"]').inputValue(),'');
  await page.getByRole('navigation').getByRole('menuitem',{name:'物品档案'}).click();
  await page.getByRole('heading',{name:'物品档案'}).waitFor();
  assert.ok(await page.locator('.enhanced-filter[data-filter-control="itemsCat"] .el-select').count(),'列表分类使用统一下拉控件');
  const itemFilterWidths=await page.locator('.list-filter-field').evaluateAll(els=>els.map(el=>Math.round(el.getBoundingClientRect().width)));
  assert.ok(itemFilterWidths.every(width=>Math.abs(width-itemFilterWidths[0])<=1),'物品档案筛选条件等宽');
  await page.locator('[data-filter="itemsQ"]').fill('鼠标');
  assert.ok(await page.locator('.card tbody tr').count()>1,'输入条件前列表保持不变');
  await page.locator('[data-action="searchFilters"]').click();
  assert.equal(await page.locator('.card tbody tr').count(),1,'点击搜索后应用物品筛选');
  await page.locator('[data-action="clearFilters"]').click();
  assert.ok(await page.locator('.card tbody tr').count()>1,'重置恢复完整列表');
  await setRole('employee');
  assert.equal(await page.locator('[data-action="newItem"]').isDisabled(),true,'员工不能维护物品档案');
  await page.getByRole('navigation').getByRole('menuitem',{name:/库存预警/}).click();
  assert.ok(await page.getByText('待采购',{exact:true}).count(),'已有采购流程的预警显示处理状态');
  await page.locator('[data-action="purchaseFor:i8"]').click();
  assert.ok(await page.locator('#dialogForm [data-enhanced="expected"] + .enhanced-control .el-date-editor').count(),'采购日期使用统一日期控件');
  assert.ok(await page.locator('#dialogForm [data-enhanced="dept"] + .enhanced-control .el-select').count(),'申请部门使用下拉选择');
  assert.ok(await page.locator('#dialogForm .required-star').count()>=4,'必填标签显示红色星号');
  await page.locator('[data-add-line]').click();
  assert.equal(await page.locator('#requestLines .line-item').count(),2,'可添加采购明细');
  await page.locator('#requestLines .line-item').last().locator('[data-remove-line]').click();
  assert.equal(await page.locator('#requestLines .line-item').count(),1,'可移除采购明细');
  await page.locator('#dialogForm [name="purpose"]').fill('自动化采购测试');
  await page.locator('#requestLines [name="qty"]').fill('5');
  await page.getByRole('button',{name:'保存草稿'}).click();
  await page.locator('[data-action^="submitRequest:"]').last().click();
  assert.equal(await page.locator('[data-action^="approveRequest:"]').last().isDisabled(),true,'员工不能审批采购申请');
  await setRole('managerAdmin');
  assert.equal(await page.locator('[data-action^="approveRequest:"]').last().isDisabled(),true,'跨部门负责人不能审批');
  await setRole('manager');
  await page.locator('[data-action^="approveRequest:"]').last().click();
  await page.getByRole('navigation').getByRole('menuitem',{name:'采购处理'}).click();
  assert.equal(await page.locator('[data-action^="receiveTask:"]').first().isDisabled(),true,'负责人不能处理到货');
  await setRole('buyer');
  await page.locator('[data-action^="receiveTask:"]').first().click();
  await page.locator('#dialogForm [name="qty"]').fill('2');
  await setSupplier('演示供应商');
  await page.locator('#dialogForm [name="price"]').fill('12.5');
  await page.getByRole('button',{name:'确认入库'}).click();
  await page.locator('.business-dialog').waitFor({state:'hidden'});
  assert.ok(await page.evaluate(()=>JSON.parse(localStorage.getItem('cangxu-demo-v1')).suppliers.includes('演示供应商')),'新供应商保存后可复用');
  if(await page.locator('.business-dialog').count())throw new Error('到货入库弹窗未关闭: '+await page.locator('.business-dialog').innerText()+' / '+await page.locator('#toastRoot').innerText()+' / '+JSON.stringify(await page.locator('#dialogForm').evaluate(form=>Object.fromEntries(new FormData(form)))));
  await page.getByRole('navigation').getByRole('menuitem',{name:'物品档案'}).click();
  let stock=await page.evaluate(()=>JSON.parse(localStorage.getItem('cangxu-demo-v1')).items.find(x=>x.id==='i3').stock);
  assert.equal(stock,10,'部分到货只增加实际到货 2 件');
  await setRole('employee');
  await page.getByRole('navigation').getByRole('menuitem',{name:'领用出库'}).click();
  await page.locator('[data-action="newIssue"]').click();
  await selectDialog('itemId','中性签字笔');
  await page.locator('#dialogForm [name="qty"]').fill('1');
  await page.locator('#dialogForm [name="purpose"]').fill('测试领用');
  await page.getByRole('button',{name:'提交申请'}).click();
  assert.equal(await page.locator('[data-action^="approveIssue:"]').first().isDisabled(),true,'员工不能审核领用');
  await setRole('warehouse');
  await page.locator('[data-action^="approveIssue:"]').first().click();
  await page.locator('[data-action^="outIssue:"]').first().click();
  await page.waitForFunction(()=>JSON.parse(localStorage.getItem('cangxu-demo-v1')).items.find(i=>i.id==='i2').stock===17);
  const result=await page.evaluate(()=>{let x=JSON.parse(localStorage.getItem('cangxu-demo-v1'));return {stock:x.items.find(i=>i.id==='i2').stock,movements:x.movements.length,tasks:x.tasks.length}});
  assert.equal(result.stock,17);assert.ok(result.movements>=4);assert.ok(result.tasks>=2);assert.deepEqual(errors,[]);
  const issuedId=await page.evaluate(()=>JSON.parse(localStorage.getItem('cangxu-demo-v1')).issues.at(-1).id);
  await page.locator(`[data-action="returnIssue:${issuedId}"]`).click();
  assert.equal(await page.locator('#dialogForm [name="type"]').inputValue(),'退货入库');
  assert.equal(await page.locator('#dialogForm [name="issueId"]').inputValue(),issuedId);
  await page.locator('#dialogForm [name="qty"]').fill('1');
  await page.locator('#dialogForm [name="reason"]').fill('归还未使用物品');
  await page.getByRole('button',{name:'确认入库 / 调整'}).click();
  await page.waitForFunction(()=>JSON.parse(localStorage.getItem('cangxu-demo-v1')).items.find(i=>i.id==='i2').stock===18);
  assert.equal(await page.evaluate((id)=>JSON.parse(localStorage.getItem('cangxu-demo-v1')).movements.some(m=>m.type==='退货入库'&&m.issueId===id),issuedId),true);
  await page.getByRole('navigation').getByRole('menuitem',{name:'入库管理'}).click();
  await page.locator('[data-action^="inboundDetail:"]').first().click();
  await page.getByRole('heading',{name:'入库详情'}).waitFor();
  assert.ok(await page.getByText('入库金额',{exact:true}).count(),'入库详情展示金额与完整信息');
  await page.getByRole('button',{name:'取消'}).click();
  await page.locator('[data-action="newInbound"]').click();
  await selectDialog('type','退货入库');
  assert.equal(await page.locator(`#dialogForm [data-enhanced="issueId"] + .enhanced-control`).innerText().then(x=>x.includes(issuedId)),false,'全部退回后不能重复退回');
  await page.getByRole('button',{name:'取消'}).click();
  await page.locator('[data-action="newInbound"]').click();
  await selectDialog('itemId','中性签字笔');
  await page.locator('#dialogForm [name="qty"]').fill('10');
  await page.locator('#dialogForm [name="reason"]').fill('恢复安全库存');
  await page.getByRole('button',{name:'确认入库 / 调整'}).click();
  assert.equal(await page.locator('.business-dialog').count(),1,'未填供应商和批次时采购入库不能提交');
  await setSupplier('办公供应商');
  await page.locator('#dialogForm [name="batch"]').fill('B-RESTORE-01');
  await page.locator('#dialogForm [name="price"]').fill('18');
  await page.getByRole('button',{name:'确认入库 / 调整'}).click();
  await page.getByRole('navigation').getByRole('menuitem',{name:/库存预警/}).click();
  assert.equal(await page.locator('[data-action="purchaseFor:i2"]').count(),0,'库存恢复后自动解除预警');
  await page.getByRole('navigation').getByRole('menuitem',{name:'入库管理'}).click();
  for(const [batch,offset] of [['EXP-SOON',10],['EXP-LATER',90]]){
    await page.locator('[data-action="newInbound"]').click();
    await selectDialog('itemId','机械键盘');
    await page.locator('#dialogForm [name="qty"]').fill('1');
    await setSupplier('设备供应商');
    await page.locator('#dialogForm [name="batch"]').fill(batch);
    await page.locator('#dialogForm [name="price"]').fill('219');
    await setDate('expiry',new Date(Date.now()+offset*86400000).toISOString().slice(0,10));
    await page.locator('#dialogForm [name="reason"]').fill('测试批次有效期');
    await page.getByRole('button',{name:'确认入库 / 调整'}).click();
  }
  await page.getByRole('navigation').getByRole('menuitem',{name:/库存预警/}).click();
  assert.ok(await page.locator('[data-action="purchaseFor:i4"]').count()>0,'后到的远期批次不能覆盖临期批次预警');
  await page.getByRole('navigation').getByRole('menuitem',{name:'入库管理'}).click();
  await page.locator('[data-action="newInbound"]').click();
  await selectDialog('type','库存调整');
  await selectDialog('itemId','机械键盘');
  await page.locator('#dialogForm [name="qty"]').fill('-1');
  await page.locator('#dialogForm [name="reason"]').fill('优先处理临期批次');
  await page.getByRole('button',{name:'确认入库 / 调整'}).click();
  await page.getByRole('navigation').getByRole('menuitem',{name:/库存预警/}).click();
  assert.equal(await page.locator('[data-action="purchaseFor:i4"]').count(),0,'临期批次耗尽后预警自动解除');
  await page.getByRole('navigation').getByRole('menuitem',{name:'入库管理'}).click();
  await page.locator('[data-action="newInbound"]').click();
  await selectDialog('itemId','机械键盘');
  await page.locator('#dialogForm [name="qty"]').fill('1');
  await setSupplier('设备供应商');
  await page.locator('#dialogForm [name="batch"]').fill('EXP-PAST');
  await page.locator('#dialogForm [name="price"]').fill('219');
  await setDate('expiry',new Date(Date.now()-2*86400000).toISOString().slice(0,10));
  await page.locator('#dialogForm [name="reason"]').fill('测试已过期批次');
  await page.getByRole('button',{name:'确认入库 / 调整'}).click();
  await page.getByRole('navigation').getByRole('menuitem',{name:/库存预警/}).click();
  const expiredRow=page.locator('tr').filter({has:page.locator('[data-action="purchaseFor:i4"]')});
  assert.match(await expiredRow.innerText(),/已过期/,'过期批次应单独标记为已过期');
  assert.doesNotMatch(await expiredRow.innerText(),/即将过期/,'过期批次不应误标为即将过期');
  await page.locator('.enhanced-filter[data-filter-control="alertType"] .el-select').click();
  await page.locator('.el-select-dropdown__item:visible').filter({hasText:'已过期'}).click();
  await page.locator('[data-action="searchFilters"]').click();
  assert.equal(await page.locator('[data-action="purchaseFor:i4"]').count(),1,'可单独筛选已过期预警');
  await page.getByRole('navigation').getByRole('menuitem',{name:'入库管理'}).click();
  await page.locator('[data-action="newInbound"]').click();
  await selectDialog('type','库存调整');
  await selectDialog('itemId','机械键盘');
  await page.locator('#dialogForm [name="qty"]').fill('-1');
  await page.locator('#dialogForm [name="reason"]').fill('隔离处理过期批次');
  await page.getByRole('button',{name:'确认入库 / 调整'}).click();
  await page.getByRole('navigation').getByRole('menuitem',{name:/库存预警/}).click();
  assert.equal(await page.locator('[data-action="purchaseFor:i4"]').count(),0,'过期批次耗尽后预警自动解除');
  await page.getByRole('navigation').getByRole('menuitem',{name:'物品档案'}).click();
  await page.locator('[data-action="toggleItem:i2"]').click();
  await page.getByRole('navigation').getByRole('menuitem',{name:'领用出库'}).click();
  await page.locator('[data-action="newIssue"]').click();
  await page.locator('#dialogForm [data-enhanced="itemId"] + .enhanced-control .el-select').click();
  assert.equal(await page.locator('.el-select-dropdown__item:visible').filter({hasText:'中性签字笔'}).count(),0,'停用物品不可继续申请领用');
  await page.getByRole('button',{name:'取消'}).click();
  await page.getByRole('navigation').getByRole('menuitem',{name:'库存记录与统计'}).click();
  const recordFilterWidths=await page.locator('.record-filter-field').evaluateAll(els=>els.map(el=>Math.round(el.getBoundingClientRect().width)));
  assert.ok(recordFilterWidths.every(width=>Math.abs(width-recordFilterWidths[0])<=1),'库存流水筛选条件等宽');
  await page.locator('[data-filter="recQ"]').fill('中性签字笔');
  await page.locator('.records-filters [data-action="searchFilters"]').click();
  const downloadPromise=page.waitForEvent('download');
  await page.locator('[data-action="exportRecords"]').first().click();
  const download=await downloadPromise;
  assert.match(download.suggestedFilename(),/好财-库存流水-.*\.csv$/);
  const csv=await readFile(await download.path(),'utf8');
  assert.ok(csv.includes('中性签字笔'));
  assert.ok(!csv.includes('A4 复印纸'));
  await page.locator('[data-action="recordTab:issues"]').click();
  await page.locator('[data-filter="personQ"]').fill('陈小雨');
  await page.locator('.records-filters [data-action="searchFilters"]').click();
  assert.ok(await page.locator('.records-panel tbody tr').count()>0,'可查看个人领用明细');
  await page.locator('.enhanced-filter[data-filter-control="recDept"] .el-select').click();
  await page.locator('.el-select-dropdown__item:visible').filter({hasText:'行政部'}).click();
  await page.locator('.records-filters [data-action="searchFilters"]').click();
  assert.ok(await page.locator('.records-panel .empty').count()>0,'可按部门筛选领用明细');
  await page.locator('.enhanced-filter[data-filter-control="recDept"] .el-select').click();
  await page.locator('.el-select-dropdown__item:visible').filter({hasText:'产品部'}).click();
  await page.locator('.records-filters [data-action="searchFilters"]').click();
  assert.ok(await page.locator('.records-panel tbody tr').count()>0,'切换部门后恢复匹配的领用明细');
  const issueDownloadPromise=page.waitForEvent('download');
  await page.locator('[data-action="exportRecords"]').click();
  const issueDownload=await issueDownloadPromise;
  assert.match(issueDownload.suggestedFilename(),/好财-领用明细-.*\.csv$/);
  const issueCsv=await readFile(await issueDownload.path(),'utf8');
  assert.ok(issueCsv.includes('陈小雨'));
  console.log('PASS 页面渲染、外观设置、全局搜索、筛选重置、采购审批、分批到货、领用出库、预警与 CSV 导出');
}finally{await browser.close()}
